// Wire contract shared by the clawson daemon (Go), the TUI (Go), and the
// Android client (Kotlin). Generated Go code lands in ./pb (committed; run
// `make proto-gen`). Field names are snake_case to match the historical JSON
// keys the TUI still consumes via protojson(UseProtoNames:true).
//
// Conventions:
//   - proto3 scalar zero-values are not serialized, reproducing the old
//     `omitempty` behavior on the wire.
//   - protobuf has no struct embedding, so the old BaseResp{ok,error} is
//     flattened into every *Resp as fields 1 and 2.
//   - `ts` and schedule timestamps stay `double` (Python time.time() seconds);
//     History pages compare ts < before, so the float contract must hold.
//   - arbitrary JSON objects (config, metrics) map to google.protobuf.Struct.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: clawson.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Clawson_Spawn_FullMethodName          = "/clawson.Clawson/Spawn"
	Clawson_Send_FullMethodName           = "/clawson.Clawson/Send"
	Clawson_List_FullMethodName           = "/clawson.Clawson/List"
	Clawson_Stop_FullMethodName           = "/clawson.Clawson/Stop"
	Clawson_Interrupt_FullMethodName      = "/clawson.Clawson/Interrupt"
	Clawson_Destroy_FullMethodName        = "/clawson.Clawson/Destroy"
	Clawson_Restart_FullMethodName        = "/clawson.Clawson/Restart"
	Clawson_History_FullMethodName        = "/clawson.Clawson/History"
	Clawson_Config_FullMethodName         = "/clawson.Clawson/Config"
	Clawson_Metrics_FullMethodName        = "/clawson.Clawson/Metrics"
	Clawson_Clear_FullMethodName          = "/clawson.Clawson/Clear"
	Clawson_Skills_FullMethodName         = "/clawson.Clawson/Skills"
	Clawson_SkillNew_FullMethodName       = "/clawson.Clawson/SkillNew"
	Clawson_SkillRead_FullMethodName      = "/clawson.Clawson/SkillRead"
	Clawson_SchedAdd_FullMethodName       = "/clawson.Clawson/SchedAdd"
	Clawson_SchedList_FullMethodName      = "/clawson.Clawson/SchedList"
	Clawson_SchedDel_FullMethodName       = "/clawson.Clawson/SchedDel"
	Clawson_SchedToggle_FullMethodName    = "/clawson.Clawson/SchedToggle"
	Clawson_SchedRun_FullMethodName       = "/clawson.Clawson/SchedRun"
	Clawson_AclGet_FullMethodName         = "/clawson.Clawson/AclGet"
	Clawson_AclSetRole_FullMethodName     = "/clawson.Clawson/AclSetRole"
	Clawson_AclDelRole_FullMethodName     = "/clawson.Clawson/AclDelRole"
	Clawson_SubscribeGroup_FullMethodName = "/clawson.Clawson/SubscribeGroup"
	Clawson_SubscribeLogs_FullMethodName  = "/clawson.Clawson/SubscribeLogs"
	Clawson_WatchState_FullMethodName     = "/clawson.Clawson/WatchState"
)

// ClawsonClient is the client API for Clawson service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClawsonClient interface {
	// ---- unary (one per legacy dispatch case) ----
	Spawn(ctx context.Context, in *SpawnReq, opts ...grpc.CallOption) (*SpawnResp, error)
	Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*BaseResp, error)
	List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error)
	Stop(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error)
	Interrupt(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error)
	Destroy(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error)
	Restart(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*SpawnResp, error)
	History(ctx context.Context, in *HistoryReq, opts ...grpc.CallOption) (*HistoryResp, error)
	Config(ctx context.Context, in *ConfigReq, opts ...grpc.CallOption) (*ConfigResp, error)
	Metrics(ctx context.Context, in *MetricsReq, opts ...grpc.CallOption) (*MetricsResp, error)
	Clear(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error)
	Skills(ctx context.Context, in *SkillListReq, opts ...grpc.CallOption) (*SkillsResp, error)
	SkillNew(ctx context.Context, in *SkillNewReq, opts ...grpc.CallOption) (*SkillNewResp, error)
	SkillRead(ctx context.Context, in *SkillReadReq, opts ...grpc.CallOption) (*SkillReadResp, error)
	SchedAdd(ctx context.Context, in *SchedAddReq, opts ...grpc.CallOption) (*SchedAddResp, error)
	SchedList(ctx context.Context, in *SchedListReq, opts ...grpc.CallOption) (*SchedListResp, error)
	SchedDel(ctx context.Context, in *SchedIDReq, opts ...grpc.CallOption) (*BaseResp, error)
	SchedToggle(ctx context.Context, in *SchedToggleReq, opts ...grpc.CallOption) (*BaseResp, error)
	SchedRun(ctx context.Context, in *SchedIDReq, opts ...grpc.CallOption) (*BaseResp, error)
	// ---- ACL management (HARDCODED admin-only: these verbs can never be
	// granted via acl.json — a role granting itself acl_set_role would be
	// privilege escalation to full control; see daemon/acl.go) ----
	AclGet(ctx context.Context, in *AclGetReq, opts ...grpc.CallOption) (*AclResp, error)
	AclSetRole(ctx context.Context, in *AclSetRoleReq, opts ...grpc.CallOption) (*AclResp, error)
	AclDelRole(ctx context.Context, in *AclDelRoleReq, opts ...grpc.CallOption) (*AclResp, error)
	// ---- server-streaming (the old connection-ownership-transfer cases) ----
	// Stream-open replaces the old {ok,subscribed} ack frame. A bad group or
	// failed auth surfaces as a non-OK gRPC status at open time.
	SubscribeGroup(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	SubscribeLogs(ctx context.Context, in *LogsReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEvent], error)
	// WatchState pushes a full group-state snapshot whenever it changes
	// (spawn/stop/stall/queue-depth/config), replacing client-side List
	// polling. The first frame arrives immediately; later frames only on
	// change. Snapshots are idempotent — a client may miss intermediate
	// frames and still converge on the latest one.
	WatchState(ctx context.Context, in *WatchReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateFrame], error)
}

type clawsonClient struct {
	cc grpc.ClientConnInterface
}

func NewClawsonClient(cc grpc.ClientConnInterface) ClawsonClient {
	return &clawsonClient{cc}
}

func (c *clawsonClient) Spawn(ctx context.Context, in *SpawnReq, opts ...grpc.CallOption) (*SpawnResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnResp)
	err := c.cc.Invoke(ctx, Clawson_Spawn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Clawson_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResp)
	err := c.cc.Invoke(ctx, Clawson_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) Stop(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Clawson_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) Interrupt(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Clawson_Interrupt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) Destroy(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Clawson_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) Restart(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*SpawnResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnResp)
	err := c.cc.Invoke(ctx, Clawson_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) History(ctx context.Context, in *HistoryReq, opts ...grpc.CallOption) (*HistoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResp)
	err := c.cc.Invoke(ctx, Clawson_History_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) Config(ctx context.Context, in *ConfigReq, opts ...grpc.CallOption) (*ConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResp)
	err := c.cc.Invoke(ctx, Clawson_Config_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) Metrics(ctx context.Context, in *MetricsReq, opts ...grpc.CallOption) (*MetricsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResp)
	err := c.cc.Invoke(ctx, Clawson_Metrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) Clear(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Clawson_Clear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) Skills(ctx context.Context, in *SkillListReq, opts ...grpc.CallOption) (*SkillsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillsResp)
	err := c.cc.Invoke(ctx, Clawson_Skills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) SkillNew(ctx context.Context, in *SkillNewReq, opts ...grpc.CallOption) (*SkillNewResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillNewResp)
	err := c.cc.Invoke(ctx, Clawson_SkillNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) SkillRead(ctx context.Context, in *SkillReadReq, opts ...grpc.CallOption) (*SkillReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillReadResp)
	err := c.cc.Invoke(ctx, Clawson_SkillRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) SchedAdd(ctx context.Context, in *SchedAddReq, opts ...grpc.CallOption) (*SchedAddResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedAddResp)
	err := c.cc.Invoke(ctx, Clawson_SchedAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) SchedList(ctx context.Context, in *SchedListReq, opts ...grpc.CallOption) (*SchedListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedListResp)
	err := c.cc.Invoke(ctx, Clawson_SchedList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) SchedDel(ctx context.Context, in *SchedIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Clawson_SchedDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) SchedToggle(ctx context.Context, in *SchedToggleReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Clawson_SchedToggle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) SchedRun(ctx context.Context, in *SchedIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Clawson_SchedRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) AclGet(ctx context.Context, in *AclGetReq, opts ...grpc.CallOption) (*AclResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AclResp)
	err := c.cc.Invoke(ctx, Clawson_AclGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) AclSetRole(ctx context.Context, in *AclSetRoleReq, opts ...grpc.CallOption) (*AclResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AclResp)
	err := c.cc.Invoke(ctx, Clawson_AclSetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) AclDelRole(ctx context.Context, in *AclDelRoleReq, opts ...grpc.CallOption) (*AclResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AclResp)
	err := c.cc.Invoke(ctx, Clawson_AclDelRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawsonClient) SubscribeGroup(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Clawson_ServiceDesc.Streams[0], Clawson_SubscribeGroup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeReq, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Clawson_SubscribeGroupClient = grpc.ServerStreamingClient[Event]

func (c *clawsonClient) SubscribeLogs(ctx context.Context, in *LogsReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Clawson_ServiceDesc.Streams[1], Clawson_SubscribeLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsReq, LogEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Clawson_SubscribeLogsClient = grpc.ServerStreamingClient[LogEvent]

func (c *clawsonClient) WatchState(ctx context.Context, in *WatchReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Clawson_ServiceDesc.Streams[2], Clawson_WatchState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchReq, StateFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Clawson_WatchStateClient = grpc.ServerStreamingClient[StateFrame]

// ClawsonServer is the server API for Clawson service.
// All implementations must embed UnimplementedClawsonServer
// for forward compatibility.
type ClawsonServer interface {
	// ---- unary (one per legacy dispatch case) ----
	Spawn(context.Context, *SpawnReq) (*SpawnResp, error)
	Send(context.Context, *SendReq) (*BaseResp, error)
	List(context.Context, *ListReq) (*ListResp, error)
	Stop(context.Context, *GroupReq) (*BaseResp, error)
	Interrupt(context.Context, *GroupReq) (*BaseResp, error)
	Destroy(context.Context, *GroupReq) (*BaseResp, error)
	Restart(context.Context, *GroupReq) (*SpawnResp, error)
	History(context.Context, *HistoryReq) (*HistoryResp, error)
	Config(context.Context, *ConfigReq) (*ConfigResp, error)
	Metrics(context.Context, *MetricsReq) (*MetricsResp, error)
	Clear(context.Context, *GroupReq) (*BaseResp, error)
	Skills(context.Context, *SkillListReq) (*SkillsResp, error)
	SkillNew(context.Context, *SkillNewReq) (*SkillNewResp, error)
	SkillRead(context.Context, *SkillReadReq) (*SkillReadResp, error)
	SchedAdd(context.Context, *SchedAddReq) (*SchedAddResp, error)
	SchedList(context.Context, *SchedListReq) (*SchedListResp, error)
	SchedDel(context.Context, *SchedIDReq) (*BaseResp, error)
	SchedToggle(context.Context, *SchedToggleReq) (*BaseResp, error)
	SchedRun(context.Context, *SchedIDReq) (*BaseResp, error)
	// ---- ACL management (HARDCODED admin-only: these verbs can never be
	// granted via acl.json — a role granting itself acl_set_role would be
	// privilege escalation to full control; see daemon/acl.go) ----
	AclGet(context.Context, *AclGetReq) (*AclResp, error)
	AclSetRole(context.Context, *AclSetRoleReq) (*AclResp, error)
	AclDelRole(context.Context, *AclDelRoleReq) (*AclResp, error)
	// ---- server-streaming (the old connection-ownership-transfer cases) ----
	// Stream-open replaces the old {ok,subscribed} ack frame. A bad group or
	// failed auth surfaces as a non-OK gRPC status at open time.
	SubscribeGroup(*SubscribeReq, grpc.ServerStreamingServer[Event]) error
	SubscribeLogs(*LogsReq, grpc.ServerStreamingServer[LogEvent]) error
	// WatchState pushes a full group-state snapshot whenever it changes
	// (spawn/stop/stall/queue-depth/config), replacing client-side List
	// polling. The first frame arrives immediately; later frames only on
	// change. Snapshots are idempotent — a client may miss intermediate
	// frames and still converge on the latest one.
	WatchState(*WatchReq, grpc.ServerStreamingServer[StateFrame]) error
	mustEmbedUnimplementedClawsonServer()
}

// UnimplementedClawsonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClawsonServer struct{}

func (UnimplementedClawsonServer) Spawn(context.Context, *SpawnReq) (*SpawnResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Spawn not implemented")
}
func (UnimplementedClawsonServer) Send(context.Context, *SendReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedClawsonServer) List(context.Context, *ListReq) (*ListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedClawsonServer) Stop(context.Context, *GroupReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedClawsonServer) Interrupt(context.Context, *GroupReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Interrupt not implemented")
}
func (UnimplementedClawsonServer) Destroy(context.Context, *GroupReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedClawsonServer) Restart(context.Context, *GroupReq) (*SpawnResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedClawsonServer) History(context.Context, *HistoryReq) (*HistoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method History not implemented")
}
func (UnimplementedClawsonServer) Config(context.Context, *ConfigReq) (*ConfigResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Config not implemented")
}
func (UnimplementedClawsonServer) Metrics(context.Context, *MetricsReq) (*MetricsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Metrics not implemented")
}
func (UnimplementedClawsonServer) Clear(context.Context, *GroupReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Clear not implemented")
}
func (UnimplementedClawsonServer) Skills(context.Context, *SkillListReq) (*SkillsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Skills not implemented")
}
func (UnimplementedClawsonServer) SkillNew(context.Context, *SkillNewReq) (*SkillNewResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SkillNew not implemented")
}
func (UnimplementedClawsonServer) SkillRead(context.Context, *SkillReadReq) (*SkillReadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SkillRead not implemented")
}
func (UnimplementedClawsonServer) SchedAdd(context.Context, *SchedAddReq) (*SchedAddResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedAdd not implemented")
}
func (UnimplementedClawsonServer) SchedList(context.Context, *SchedListReq) (*SchedListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedList not implemented")
}
func (UnimplementedClawsonServer) SchedDel(context.Context, *SchedIDReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedDel not implemented")
}
func (UnimplementedClawsonServer) SchedToggle(context.Context, *SchedToggleReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedToggle not implemented")
}
func (UnimplementedClawsonServer) SchedRun(context.Context, *SchedIDReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedRun not implemented")
}
func (UnimplementedClawsonServer) AclGet(context.Context, *AclGetReq) (*AclResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AclGet not implemented")
}
func (UnimplementedClawsonServer) AclSetRole(context.Context, *AclSetRoleReq) (*AclResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AclSetRole not implemented")
}
func (UnimplementedClawsonServer) AclDelRole(context.Context, *AclDelRoleReq) (*AclResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AclDelRole not implemented")
}
func (UnimplementedClawsonServer) SubscribeGroup(*SubscribeReq, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method SubscribeGroup not implemented")
}
func (UnimplementedClawsonServer) SubscribeLogs(*LogsReq, grpc.ServerStreamingServer[LogEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeLogs not implemented")
}
func (UnimplementedClawsonServer) WatchState(*WatchReq, grpc.ServerStreamingServer[StateFrame]) error {
	return status.Error(codes.Unimplemented, "method WatchState not implemented")
}
func (UnimplementedClawsonServer) mustEmbedUnimplementedClawsonServer() {}
func (UnimplementedClawsonServer) testEmbeddedByValue()                 {}

// UnsafeClawsonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClawsonServer will
// result in compilation errors.
type UnsafeClawsonServer interface {
	mustEmbedUnimplementedClawsonServer()
}

func RegisterClawsonServer(s grpc.ServiceRegistrar, srv ClawsonServer) {
	// If the following call panics, it indicates UnimplementedClawsonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Clawson_ServiceDesc, srv)
}

func _Clawson_Spawn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).Spawn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_Spawn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).Spawn(ctx, req.(*SpawnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).Send(ctx, req.(*SendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).List(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).Stop(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_Interrupt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).Interrupt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_Interrupt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).Interrupt(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).Destroy(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).Restart(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_History_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).History(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_History_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).History(ctx, req.(*HistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_Config_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).Config(ctx, req.(*ConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_Metrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).Metrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_Metrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).Metrics(ctx, req.(*MetricsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_Clear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).Clear(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_Skills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).Skills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_Skills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).Skills(ctx, req.(*SkillListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_SkillNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillNewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).SkillNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_SkillNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).SkillNew(ctx, req.(*SkillNewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_SkillRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).SkillRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_SkillRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).SkillRead(ctx, req.(*SkillReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_SchedAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).SchedAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_SchedAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).SchedAdd(ctx, req.(*SchedAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_SchedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).SchedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_SchedList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).SchedList(ctx, req.(*SchedListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_SchedDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).SchedDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_SchedDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).SchedDel(ctx, req.(*SchedIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_SchedToggle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedToggleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).SchedToggle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_SchedToggle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).SchedToggle(ctx, req.(*SchedToggleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_SchedRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).SchedRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_SchedRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).SchedRun(ctx, req.(*SchedIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_AclGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AclGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).AclGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_AclGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).AclGet(ctx, req.(*AclGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_AclSetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AclSetRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).AclSetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_AclSetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).AclSetRole(ctx, req.(*AclSetRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_AclDelRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AclDelRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawsonServer).AclDelRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clawson_AclDelRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawsonServer).AclDelRole(ctx, req.(*AclDelRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clawson_SubscribeGroup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClawsonServer).SubscribeGroup(m, &grpc.GenericServerStream[SubscribeReq, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Clawson_SubscribeGroupServer = grpc.ServerStreamingServer[Event]

func _Clawson_SubscribeLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClawsonServer).SubscribeLogs(m, &grpc.GenericServerStream[LogsReq, LogEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Clawson_SubscribeLogsServer = grpc.ServerStreamingServer[LogEvent]

func _Clawson_WatchState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClawsonServer).WatchState(m, &grpc.GenericServerStream[WatchReq, StateFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Clawson_WatchStateServer = grpc.ServerStreamingServer[StateFrame]

// Clawson_ServiceDesc is the grpc.ServiceDesc for Clawson service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Clawson_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawson.Clawson",
	HandlerType: (*ClawsonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Spawn",
			Handler:    _Clawson_Spawn_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Clawson_Send_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Clawson_List_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Clawson_Stop_Handler,
		},
		{
			MethodName: "Interrupt",
			Handler:    _Clawson_Interrupt_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _Clawson_Destroy_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _Clawson_Restart_Handler,
		},
		{
			MethodName: "History",
			Handler:    _Clawson_History_Handler,
		},
		{
			MethodName: "Config",
			Handler:    _Clawson_Config_Handler,
		},
		{
			MethodName: "Metrics",
			Handler:    _Clawson_Metrics_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _Clawson_Clear_Handler,
		},
		{
			MethodName: "Skills",
			Handler:    _Clawson_Skills_Handler,
		},
		{
			MethodName: "SkillNew",
			Handler:    _Clawson_SkillNew_Handler,
		},
		{
			MethodName: "SkillRead",
			Handler:    _Clawson_SkillRead_Handler,
		},
		{
			MethodName: "SchedAdd",
			Handler:    _Clawson_SchedAdd_Handler,
		},
		{
			MethodName: "SchedList",
			Handler:    _Clawson_SchedList_Handler,
		},
		{
			MethodName: "SchedDel",
			Handler:    _Clawson_SchedDel_Handler,
		},
		{
			MethodName: "SchedToggle",
			Handler:    _Clawson_SchedToggle_Handler,
		},
		{
			MethodName: "SchedRun",
			Handler:    _Clawson_SchedRun_Handler,
		},
		{
			MethodName: "AclGet",
			Handler:    _Clawson_AclGet_Handler,
		},
		{
			MethodName: "AclSetRole",
			Handler:    _Clawson_AclSetRole_Handler,
		},
		{
			MethodName: "AclDelRole",
			Handler:    _Clawson_AclDelRole_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeGroup",
			Handler:       _Clawson_SubscribeGroup_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeLogs",
			Handler:       _Clawson_SubscribeLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchState",
			Handler:       _Clawson_WatchState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clawson.proto",
}
