// Wire contract shared by the clawson daemon (Go), the TUI (Go), and the
// Android client (Kotlin). Generated Go code lands in ./pb (committed; run
// `make proto-gen`). Field names are snake_case to match the historical JSON
// keys the TUI still consumes via protojson(UseProtoNames:true).
//
// Conventions:
//   - proto3 scalar zero-values are not serialized, reproducing the old
//     `omitempty` behavior on the wire.
//   - protobuf has no struct embedding, so the old BaseResp{ok,error} is
//     flattened into every *Resp as fields 1 and 2.
//   - `ts` and schedule timestamps stay `double` (Python time.time() seconds);
//     History pages compare ts < before, so the float contract must hold.
//   - arbitrary JSON objects (config, metrics) map to google.protobuf.Struct.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: clawson.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Event      string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Group      string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Ts         float64                `protobuf:"fixed64,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Msg        string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Text       string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Name       string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Input      string                 `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	Words      int32                  `protobuf:"varint,8,opt,name=words,proto3" json:"words,omitempty"`
	Body       string                 `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty"`
	Historical bool                   `protobuf:"varint,10,opt,name=historical,proto3" json:"historical,omitempty"`
	Id         string                 `protobuf:"bytes,11,opt,name=id,proto3" json:"id,omitempty"`
	// Per-group monotonic sequence number, assigned by the daemon at emit
	// time (starts at 1; resets on daemon restart). Streaming frames carry
	// it so clients can resume a broken stream gaplessly via
	// SubscribeReq.since_seq. History RPC events re-parsed from the log file
	// have seq 0 — the cursor only exists for the live stream. The synthetic
	// `gap` event (see SubscribeReq) also carries seq 0.
	Seq           uint64 `protobuf:"varint,12,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_clawson_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Event) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Event) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Event) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Event) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *Event) GetWords() int32 {
	if x != nil {
		return x.Words
	}
	return 0
}

func (x *Event) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Event) GetHistorical() bool {
	if x != nil {
		return x.Historical
	}
	return false
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"` // always "log"
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // info | warn | error | debug
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Ts            float64                `protobuf:"fixed64,4,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_clawson_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{1}
}

func (x *LogEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *LogEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEvent) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LogEvent) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Effort        string                 `protobuf:"bytes,5,opt,name=effort,proto3" json:"effort,omitempty"`
	Stalled       bool                   `protobuf:"varint,6,opt,name=stalled,proto3" json:"stalled,omitempty"`
	Queued        int32                  `protobuf:"varint,7,opt,name=queued,proto3" json:"queued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_clawson_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{2}
}

func (x *GroupInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GroupInfo) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *GroupInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GroupInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GroupInfo) GetEffort() string {
	if x != nil {
		return x.Effort
	}
	return ""
}

func (x *GroupInfo) GetStalled() bool {
	if x != nil {
		return x.Stalled
	}
	return false
}

func (x *GroupInfo) GetQueued() int32 {
	if x != nil {
		return x.Queued
	}
	return 0
}

type SkillItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillItem) Reset() {
	*x = SkillItem{}
	mi := &file_clawson_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillItem) ProtoMessage() {}

func (x *SkillItem) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillItem.ProtoReflect.Descriptor instead.
func (*SkillItem) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{3}
}

func (x *SkillItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SkillItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SkillItem) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ScheduleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Cron          string                 `protobuf:"bytes,3,opt,name=cron,proto3" json:"cron,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     float64                `protobuf:"fixed64,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastFiredAt   float64                `protobuf:"fixed64,7,opt,name=last_fired_at,json=lastFiredAt,proto3" json:"last_fired_at,omitempty"`
	NextDueAt     float64                `protobuf:"fixed64,8,opt,name=next_due_at,json=nextDueAt,proto3" json:"next_due_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleItem) Reset() {
	*x = ScheduleItem{}
	mi := &file_clawson_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleItem) ProtoMessage() {}

func (x *ScheduleItem) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleItem.ProtoReflect.Descriptor instead.
func (*ScheduleItem) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{4}
}

func (x *ScheduleItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduleItem) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ScheduleItem) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *ScheduleItem) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ScheduleItem) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ScheduleItem) GetCreatedAt() float64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ScheduleItem) GetLastFiredAt() float64 {
	if x != nil {
		return x.LastFiredAt
	}
	return 0
}

func (x *ScheduleItem) GetNextDueAt() float64 {
	if x != nil {
		return x.NextDueAt
	}
	return 0
}

type SpawnReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Main          bool                   `protobuf:"varint,2,opt,name=main,proto3" json:"main,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Size          string                 `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnReq) Reset() {
	*x = SpawnReq{}
	mi := &file_clawson_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnReq) ProtoMessage() {}

func (x *SpawnReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnReq.ProtoReflect.Descriptor instead.
func (*SpawnReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{5}
}

func (x *SpawnReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SpawnReq) GetMain() bool {
	if x != nil {
		return x.Main
	}
	return false
}

func (x *SpawnReq) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SpawnReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SpawnReq) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type SendReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Group string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Msg   string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// Optional attachments. The daemon's Send handler processes these BEFORE
	// enqueueSend, so the per-group queue still carries a plain text turn:
	//   - image: written to groups/<g>/.cs/uploads/img-<ts>.<ext>; msg body gets
	//     "\n[image: .cs/uploads/img-<ts>.<ext>]" appended so the claude CLI reads
	//     the file from its workspace.
	//   - audio: written to .cs/uploads/voice-<ts>.<ext>, transcribed server-side
	//     (whisper); the transcript becomes (or augments) the msg body. The LLM
	//     backends are text-only, so audio never reaches them directly.
	Image         []byte `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	ImageMime     string `protobuf:"bytes,4,opt,name=image_mime,json=imageMime,proto3" json:"image_mime,omitempty"` // image/jpeg | image/png | ...
	Audio         []byte `protobuf:"bytes,5,opt,name=audio,proto3" json:"audio,omitempty"`
	AudioMime     string `protobuf:"bytes,6,opt,name=audio_mime,json=audioMime,proto3" json:"audio_mime,omitempty"` // audio/mp4 | audio/ogg | ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReq) Reset() {
	*x = SendReq{}
	mi := &file_clawson_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReq) ProtoMessage() {}

func (x *SendReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReq.ProtoReflect.Descriptor instead.
func (*SendReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{6}
}

func (x *SendReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SendReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendReq) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *SendReq) GetImageMime() string {
	if x != nil {
		return x.ImageMime
	}
	return ""
}

func (x *SendReq) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *SendReq) GetAudioMime() string {
	if x != nil {
		return x.AudioMime
	}
	return ""
}

type GroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupReq) Reset() {
	*x = GroupReq{}
	mi := &file_clawson_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupReq) ProtoMessage() {}

func (x *GroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupReq.ProtoReflect.Descriptor instead.
func (*GroupReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{7}
}

func (x *GroupReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type ListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	mi := &file_clawson_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{8}
}

type LogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsReq) Reset() {
	*x = LogsReq{}
	mi := &file_clawson_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsReq) ProtoMessage() {}

func (x *LogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsReq.ProtoReflect.Descriptor instead.
func (*LogsReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{9}
}

type WatchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchReq) Reset() {
	*x = WatchReq{}
	mi := &file_clawson_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchReq) ProtoMessage() {}

func (x *WatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchReq.ProtoReflect.Descriptor instead.
func (*WatchReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{10}
}

// since_seq = 0 requests live-only delivery (the historical behavior).
// since_seq > 0 asks the daemon to first replay, from its in-memory
// per-group ring, every event with seq > since_seq — registered atomically
// with the ring snapshot, so the client sees no gap and no duplicate across
// the replay/live boundary. When the ring cannot cover the range (events
// aged out, or the daemon restarted and seq regressed), the stream starts
// with a synthetic Event{event:"gap"}: the client's view is stale beyond
// repair by replay and it should refetch via History.
type SubscribeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	SinceSeq      uint64                 `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeReq) Reset() {
	*x = SubscribeReq{}
	mi := &file_clawson_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeReq) ProtoMessage() {}

func (x *SubscribeReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeReq.ProtoReflect.Descriptor instead.
func (*SubscribeReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{11}
}

func (x *SubscribeReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SubscribeReq) GetSinceSeq() uint64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

// One WatchState frame: the same groups map List returns, pushed on change.
type StateFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        map[string]*GroupInfo  `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ts            float64                `protobuf:"fixed64,2,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateFrame) Reset() {
	*x = StateFrame{}
	mi := &file_clawson_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateFrame) ProtoMessage() {}

func (x *StateFrame) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateFrame.ProtoReflect.Descriptor instead.
func (*StateFrame) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{12}
}

func (x *StateFrame) GetGroups() map[string]*GroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *StateFrame) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type HistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`    // 0 => server default
	Before        float64                `protobuf:"fixed64,3,opt,name=before,proto3" json:"before,omitempty"` // 0 => tail page; else events with ts < before
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryReq) Reset() {
	*x = HistoryReq{}
	mi := &file_clawson_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryReq) ProtoMessage() {}

func (x *HistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryReq.ProtoReflect.Descriptor instead.
func (*HistoryReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{13}
}

func (x *HistoryReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *HistoryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *HistoryReq) GetBefore() float64 {
	if x != nil {
		return x.Before
	}
	return 0
}

// Tri-state per field (absent / clear / set), preserving the old
// json.RawMessage semantics:
//   - scalar fields use proto3 `optional` for presence: absent => not set;
//     clear => present with value ""; set => present with value.
//   - skills is a list, which has no field presence, so a oneof carries the
//     three states explicitly.
type SkillList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillList) Reset() {
	*x = SkillList{}
	mi := &file_clawson_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillList) ProtoMessage() {}

func (x *SkillList) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillList.ProtoReflect.Descriptor instead.
func (*SkillList) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{14}
}

func (x *SkillList) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConfigReq struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Group    string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Model    *string                `protobuf:"bytes,2,opt,name=model,proto3,oneof" json:"model,omitempty"`
	Effort   *string                `protobuf:"bytes,3,opt,name=effort,proto3,oneof" json:"effort,omitempty"`
	Ports    *string                `protobuf:"bytes,5,opt,name=ports,proto3,oneof" json:"ports,omitempty"`
	Provider *string                `protobuf:"bytes,7,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	Internet *string                `protobuf:"bytes,9,opt,name=internet,proto3,oneof" json:"internet,omitempty"` // none|full — applies on /restart
	Size     *string                `protobuf:"bytes,10,opt,name=size,proto3,oneof" json:"size,omitempty"`        // small|medium|large — applies on /restart
	Root     *string                `protobuf:"bytes,11,opt,name=root,proto3,oneof" json:"root,omitempty"`        // yes|no — passwordless sudo in guest; applies on /restart
	// Types that are valid to be assigned to SkillsAction:
	//
	//	*ConfigReq_SkillsClear
	//	*ConfigReq_SkillsSet
	SkillsAction  isConfigReq_SkillsAction `protobuf_oneof:"skills_action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigReq) Reset() {
	*x = ConfigReq{}
	mi := &file_clawson_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigReq) ProtoMessage() {}

func (x *ConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigReq.ProtoReflect.Descriptor instead.
func (*ConfigReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigReq) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *ConfigReq) GetEffort() string {
	if x != nil && x.Effort != nil {
		return *x.Effort
	}
	return ""
}

func (x *ConfigReq) GetPorts() string {
	if x != nil && x.Ports != nil {
		return *x.Ports
	}
	return ""
}

func (x *ConfigReq) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *ConfigReq) GetInternet() string {
	if x != nil && x.Internet != nil {
		return *x.Internet
	}
	return ""
}

func (x *ConfigReq) GetSize() string {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return ""
}

func (x *ConfigReq) GetRoot() string {
	if x != nil && x.Root != nil {
		return *x.Root
	}
	return ""
}

func (x *ConfigReq) GetSkillsAction() isConfigReq_SkillsAction {
	if x != nil {
		return x.SkillsAction
	}
	return nil
}

func (x *ConfigReq) GetSkillsClear() *emptypb.Empty {
	if x != nil {
		if x, ok := x.SkillsAction.(*ConfigReq_SkillsClear); ok {
			return x.SkillsClear
		}
	}
	return nil
}

func (x *ConfigReq) GetSkillsSet() *SkillList {
	if x != nil {
		if x, ok := x.SkillsAction.(*ConfigReq_SkillsSet); ok {
			return x.SkillsSet
		}
	}
	return nil
}

type isConfigReq_SkillsAction interface {
	isConfigReq_SkillsAction()
}

type ConfigReq_SkillsClear struct {
	SkillsClear *emptypb.Empty `protobuf:"bytes,8,opt,name=skills_clear,json=skillsClear,proto3,oneof"`
}

type ConfigReq_SkillsSet struct {
	SkillsSet *SkillList `protobuf:"bytes,4,opt,name=skills_set,json=skillsSet,proto3,oneof"`
}

func (*ConfigReq_SkillsClear) isConfigReq_SkillsAction() {}

func (*ConfigReq_SkillsSet) isConfigReq_SkillsAction() {}

type SkillListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillListReq) Reset() {
	*x = SkillListReq{}
	mi := &file_clawson_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillListReq) ProtoMessage() {}

func (x *SkillListReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillListReq.ProtoReflect.Descriptor instead.
func (*SkillListReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{16}
}

func (x *SkillListReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type SkillNewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillNewReq) Reset() {
	*x = SkillNewReq{}
	mi := &file_clawson_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillNewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillNewReq) ProtoMessage() {}

func (x *SkillNewReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillNewReq.ProtoReflect.Descriptor instead.
func (*SkillNewReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{17}
}

func (x *SkillNewReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SkillReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillReadReq) Reset() {
	*x = SkillReadReq{}
	mi := &file_clawson_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillReadReq) ProtoMessage() {}

func (x *SkillReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillReadReq.ProtoReflect.Descriptor instead.
func (*SkillReadReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{18}
}

func (x *SkillReadReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MetricsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReq) Reset() {
	*x = MetricsReq{}
	mi := &file_clawson_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReq) ProtoMessage() {}

func (x *MetricsReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReq.ProtoReflect.Descriptor instead.
func (*MetricsReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{19}
}

func (x *MetricsReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type SchedAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Cron          string                 `protobuf:"bytes,2,opt,name=cron,proto3" json:"cron,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedAddReq) Reset() {
	*x = SchedAddReq{}
	mi := &file_clawson_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedAddReq) ProtoMessage() {}

func (x *SchedAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedAddReq.ProtoReflect.Descriptor instead.
func (*SchedAddReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{20}
}

func (x *SchedAddReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SchedAddReq) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *SchedAddReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SchedListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedListReq) Reset() {
	*x = SchedListReq{}
	mi := &file_clawson_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedListReq) ProtoMessage() {}

func (x *SchedListReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedListReq.ProtoReflect.Descriptor instead.
func (*SchedListReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{21}
}

func (x *SchedListReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type SchedIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedIDReq) Reset() {
	*x = SchedIDReq{}
	mi := &file_clawson_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedIDReq) ProtoMessage() {}

func (x *SchedIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedIDReq.ProtoReflect.Descriptor instead.
func (*SchedIDReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{22}
}

func (x *SchedIDReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SchedToggleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedToggleReq) Reset() {
	*x = SchedToggleReq{}
	mi := &file_clawson_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedToggleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedToggleReq) ProtoMessage() {}

func (x *SchedToggleReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedToggleReq.ProtoReflect.Descriptor instead.
func (*SchedToggleReq) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{23}
}

func (x *SchedToggleReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SchedToggleReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_clawson_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{24}
}

func (x *BaseResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BaseResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SpawnResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnResp) Reset() {
	*x = SpawnResp{}
	mi := &file_clawson_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnResp) ProtoMessage() {}

func (x *SpawnResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnResp.ProtoReflect.Descriptor instead.
func (*SpawnResp) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{25}
}

func (x *SpawnResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SpawnResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SpawnResp) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Groups        map[string]*GroupInfo  `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResp) Reset() {
	*x = ListResp{}
	mi := &file_clawson_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResp) ProtoMessage() {}

func (x *ListResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResp.ProtoReflect.Descriptor instead.
func (*ListResp) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{26}
}

func (x *ListResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListResp) GetGroups() map[string]*GroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

type HistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Events        []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	More          bool                   `protobuf:"varint,4,opt,name=more,proto3" json:"more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResp) Reset() {
	*x = HistoryResp{}
	mi := &file_clawson_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResp) ProtoMessage() {}

func (x *HistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResp.ProtoReflect.Descriptor instead.
func (*HistoryResp) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{27}
}

func (x *HistoryResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HistoryResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HistoryResp) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *HistoryResp) GetMore() bool {
	if x != nil {
		return x.More
	}
	return false
}

type ConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResp) Reset() {
	*x = ConfigResp{}
	mi := &file_clawson_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResp) ProtoMessage() {}

func (x *ConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResp.ProtoReflect.Descriptor instead.
func (*ConfigResp) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{28}
}

func (x *ConfigResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ConfigResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ConfigResp) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type MetricsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Metric        *structpb.Struct       `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	GlobalMetric  *structpb.Struct       `protobuf:"bytes,4,opt,name=global_metric,json=globalMetric,proto3" json:"global_metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResp) Reset() {
	*x = MetricsResp{}
	mi := &file_clawson_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResp) ProtoMessage() {}

func (x *MetricsResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResp.ProtoReflect.Descriptor instead.
func (*MetricsResp) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{29}
}

func (x *MetricsResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MetricsResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MetricsResp) GetMetric() *structpb.Struct {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *MetricsResp) GetGlobalMetric() *structpb.Struct {
	if x != nil {
		return x.GlobalMetric
	}
	return nil
}

type SkillsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Skills        []*SkillItem           `protobuf:"bytes,3,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillsResp) Reset() {
	*x = SkillsResp{}
	mi := &file_clawson_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillsResp) ProtoMessage() {}

func (x *SkillsResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillsResp.ProtoReflect.Descriptor instead.
func (*SkillsResp) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{30}
}

func (x *SkillsResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SkillsResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SkillsResp) GetSkills() []*SkillItem {
	if x != nil {
		return x.Skills
	}
	return nil
}

type SkillNewResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillNewResp) Reset() {
	*x = SkillNewResp{}
	mi := &file_clawson_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillNewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillNewResp) ProtoMessage() {}

func (x *SkillNewResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillNewResp.ProtoReflect.Descriptor instead.
func (*SkillNewResp) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{31}
}

func (x *SkillNewResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SkillNewResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SkillNewResp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SkillReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillReadResp) Reset() {
	*x = SkillReadResp{}
	mi := &file_clawson_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillReadResp) ProtoMessage() {}

func (x *SkillReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillReadResp.ProtoReflect.Descriptor instead.
func (*SkillReadResp) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{32}
}

func (x *SkillReadResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SkillReadResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SkillReadResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillReadResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SchedAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Item          *ScheduleItem          `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedAddResp) Reset() {
	*x = SchedAddResp{}
	mi := &file_clawson_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedAddResp) ProtoMessage() {}

func (x *SchedAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedAddResp.ProtoReflect.Descriptor instead.
func (*SchedAddResp) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{33}
}

func (x *SchedAddResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SchedAddResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SchedAddResp) GetItem() *ScheduleItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type SchedListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Schedules     []*ScheduleItem        `protobuf:"bytes,3,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedListResp) Reset() {
	*x = SchedListResp{}
	mi := &file_clawson_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedListResp) ProtoMessage() {}

func (x *SchedListResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawson_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedListResp.ProtoReflect.Descriptor instead.
func (*SchedListResp) Descriptor() ([]byte, []int) {
	return file_clawson_proto_rawDescGZIP(), []int{34}
}

func (x *SchedListResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SchedListResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SchedListResp) GetSchedules() []*ScheduleItem {
	if x != nil {
		return x.Schedules
	}
	return nil
}

var File_clawson_proto protoreflect.FileDescriptor

const file_clawson_proto_rawDesc = "" +
	"\n" +
	"\rclawson.proto\x12\aclawson\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xff\x01\n" +
	"\x05Event\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x01R\x02ts\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\a \x01(\tR\x05input\x12\x14\n" +
	"\x05words\x18\b \x01(\x05R\x05words\x12\x12\n" +
	"\x04body\x18\t \x01(\tR\x04body\x12\x1e\n" +
	"\n" +
	"historical\x18\n" +
	" \x01(\bR\n" +
	"historical\x12\x0e\n" +
	"\x02id\x18\v \x01(\tR\x02id\x12\x10\n" +
	"\x03seq\x18\f \x01(\x04R\x03seq\"X\n" +
	"\bLogEvent\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x01R\x02ts\"\xb5\x01\n" +
	"\tGroupInfo\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x16\n" +
	"\x06effort\x18\x05 \x01(\tR\x06effort\x12\x18\n" +
	"\astalled\x18\x06 \x01(\bR\astalled\x12\x16\n" +
	"\x06queued\x18\a \x01(\x05R\x06queued\"o\n" +
	"\tSkillItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\"\xd7\x01\n" +
	"\fScheduleItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x12\n" +
	"\x04cron\x18\x03 \x01(\tR\x04cron\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x01R\tcreatedAt\x12\"\n" +
	"\rlast_fired_at\x18\a \x01(\x01R\vlastFiredAt\x12\x1e\n" +
	"\vnext_due_at\x18\b \x01(\x01R\tnextDueAt\"z\n" +
	"\bSpawnReq\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x12\n" +
	"\x04main\x18\x02 \x01(\bR\x04main\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04size\x18\x05 \x01(\tR\x04size\"\x9b\x01\n" +
	"\aSendReq\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05image\x18\x03 \x01(\fR\x05image\x12\x1d\n" +
	"\n" +
	"image_mime\x18\x04 \x01(\tR\timageMime\x12\x14\n" +
	"\x05audio\x18\x05 \x01(\fR\x05audio\x12\x1d\n" +
	"\n" +
	"audio_mime\x18\x06 \x01(\tR\taudioMime\" \n" +
	"\bGroupReq\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\"\t\n" +
	"\aListReq\"\t\n" +
	"\aLogsReq\"\n" +
	"\n" +
	"\bWatchReq\"A\n" +
	"\fSubscribeReq\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1b\n" +
	"\tsince_seq\x18\x02 \x01(\x04R\bsinceSeq\"\xa4\x01\n" +
	"\n" +
	"StateFrame\x127\n" +
	"\x06groups\x18\x01 \x03(\v2\x1f.clawson.StateFrame.GroupsEntryR\x06groups\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x01R\x02ts\x1aM\n" +
	"\vGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.clawson.GroupInfoR\x05value:\x028\x01\"P\n" +
	"\n" +
	"HistoryReq\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06before\x18\x03 \x01(\x01R\x06before\"!\n" +
	"\tSkillList\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\"\xb6\x03\n" +
	"\tConfigReq\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x19\n" +
	"\x05model\x18\x02 \x01(\tH\x01R\x05model\x88\x01\x01\x12\x1b\n" +
	"\x06effort\x18\x03 \x01(\tH\x02R\x06effort\x88\x01\x01\x12\x19\n" +
	"\x05ports\x18\x05 \x01(\tH\x03R\x05ports\x88\x01\x01\x12\x1f\n" +
	"\bprovider\x18\a \x01(\tH\x04R\bprovider\x88\x01\x01\x12\x1f\n" +
	"\binternet\x18\t \x01(\tH\x05R\binternet\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\n" +
	" \x01(\tH\x06R\x04size\x88\x01\x01\x12\x17\n" +
	"\x04root\x18\v \x01(\tH\aR\x04root\x88\x01\x01\x12;\n" +
	"\fskills_clear\x18\b \x01(\v2\x16.google.protobuf.EmptyH\x00R\vskillsClear\x123\n" +
	"\n" +
	"skills_set\x18\x04 \x01(\v2\x12.clawson.SkillListH\x00R\tskillsSetB\x0f\n" +
	"\rskills_actionB\b\n" +
	"\x06_modelB\t\n" +
	"\a_effortB\b\n" +
	"\x06_portsB\v\n" +
	"\t_providerB\v\n" +
	"\t_internetB\a\n" +
	"\x05_sizeB\a\n" +
	"\x05_root\"$\n" +
	"\fSkillListReq\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\"!\n" +
	"\vSkillNewReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\fSkillReadReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\n" +
	"MetricsReq\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\"I\n" +
	"\vSchedAddReq\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x12\n" +
	"\x04cron\x18\x02 \x01(\tR\x04cron\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"$\n" +
	"\fSchedListReq\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\"\x1c\n" +
	"\n" +
	"SchedIDReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x0eSchedToggleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"0\n" +
	"\bBaseResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"E\n" +
	"\tSpawnResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"\xb6\x01\n" +
	"\bListResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x125\n" +
	"\x06groups\x18\x03 \x03(\v2\x1d.clawson.ListResp.GroupsEntryR\x06groups\x1aM\n" +
	"\vGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.clawson.GroupInfoR\x05value:\x028\x01\"o\n" +
	"\vHistoryResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12&\n" +
	"\x06events\x18\x03 \x03(\v2\x0e.clawson.EventR\x06events\x12\x12\n" +
	"\x04more\x18\x04 \x01(\bR\x04more\"c\n" +
	"\n" +
	"ConfigResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\"\xa2\x01\n" +
	"\vMetricsResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12/\n" +
	"\x06metric\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06metric\x12<\n" +
	"\rglobal_metric\x18\x04 \x01(\v2\x17.google.protobuf.StructR\fglobalMetric\"^\n" +
	"\n" +
	"SkillsResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12*\n" +
	"\x06skills\x18\x03 \x03(\v2\x12.clawson.SkillItemR\x06skills\"H\n" +
	"\fSkillNewResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"c\n" +
	"\rSkillReadResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"_\n" +
	"\fSchedAddResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\x04item\x18\x03 \x01(\v2\x15.clawson.ScheduleItemR\x04item\"j\n" +
	"\rSchedListResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x123\n" +
	"\tschedules\x18\x03 \x03(\v2\x15.clawson.ScheduleItemR\tschedules2\x93\t\n" +
	"\aClawson\x12.\n" +
	"\x05Spawn\x12\x11.clawson.SpawnReq\x1a\x12.clawson.SpawnResp\x12+\n" +
	"\x04Send\x12\x10.clawson.SendReq\x1a\x11.clawson.BaseResp\x12+\n" +
	"\x04List\x12\x10.clawson.ListReq\x1a\x11.clawson.ListResp\x12,\n" +
	"\x04Stop\x12\x11.clawson.GroupReq\x1a\x11.clawson.BaseResp\x121\n" +
	"\tInterrupt\x12\x11.clawson.GroupReq\x1a\x11.clawson.BaseResp\x12/\n" +
	"\aDestroy\x12\x11.clawson.GroupReq\x1a\x11.clawson.BaseResp\x120\n" +
	"\aRestart\x12\x11.clawson.GroupReq\x1a\x12.clawson.SpawnResp\x124\n" +
	"\aHistory\x12\x13.clawson.HistoryReq\x1a\x14.clawson.HistoryResp\x121\n" +
	"\x06Config\x12\x12.clawson.ConfigReq\x1a\x13.clawson.ConfigResp\x124\n" +
	"\aMetrics\x12\x13.clawson.MetricsReq\x1a\x14.clawson.MetricsResp\x12-\n" +
	"\x05Clear\x12\x11.clawson.GroupReq\x1a\x11.clawson.BaseResp\x124\n" +
	"\x06Skills\x12\x15.clawson.SkillListReq\x1a\x13.clawson.SkillsResp\x127\n" +
	"\bSkillNew\x12\x14.clawson.SkillNewReq\x1a\x15.clawson.SkillNewResp\x12:\n" +
	"\tSkillRead\x12\x15.clawson.SkillReadReq\x1a\x16.clawson.SkillReadResp\x127\n" +
	"\bSchedAdd\x12\x14.clawson.SchedAddReq\x1a\x15.clawson.SchedAddResp\x12:\n" +
	"\tSchedList\x12\x15.clawson.SchedListReq\x1a\x16.clawson.SchedListResp\x122\n" +
	"\bSchedDel\x12\x13.clawson.SchedIDReq\x1a\x11.clawson.BaseResp\x129\n" +
	"\vSchedToggle\x12\x17.clawson.SchedToggleReq\x1a\x11.clawson.BaseResp\x122\n" +
	"\bSchedRun\x12\x13.clawson.SchedIDReq\x1a\x11.clawson.BaseResp\x129\n" +
	"\x0eSubscribeGroup\x12\x15.clawson.SubscribeReq\x1a\x0e.clawson.Event0\x01\x126\n" +
	"\rSubscribeLogs\x12\x10.clawson.LogsReq\x1a\x11.clawson.LogEvent0\x01\x126\n" +
	"\n" +
	"WatchState\x12\x11.clawson.WatchReq\x1a\x13.clawson.StateFrame0\x01B\x18Z\x16clawson-protocol/pb;pbb\x06proto3"

var (
	file_clawson_proto_rawDescOnce sync.Once
	file_clawson_proto_rawDescData []byte
)

func file_clawson_proto_rawDescGZIP() []byte {
	file_clawson_proto_rawDescOnce.Do(func() {
		file_clawson_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clawson_proto_rawDesc), len(file_clawson_proto_rawDesc)))
	})
	return file_clawson_proto_rawDescData
}

var file_clawson_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_clawson_proto_goTypes = []any{
	(*Event)(nil),           // 0: clawson.Event
	(*LogEvent)(nil),        // 1: clawson.LogEvent
	(*GroupInfo)(nil),       // 2: clawson.GroupInfo
	(*SkillItem)(nil),       // 3: clawson.SkillItem
	(*ScheduleItem)(nil),    // 4: clawson.ScheduleItem
	(*SpawnReq)(nil),        // 5: clawson.SpawnReq
	(*SendReq)(nil),         // 6: clawson.SendReq
	(*GroupReq)(nil),        // 7: clawson.GroupReq
	(*ListReq)(nil),         // 8: clawson.ListReq
	(*LogsReq)(nil),         // 9: clawson.LogsReq
	(*WatchReq)(nil),        // 10: clawson.WatchReq
	(*SubscribeReq)(nil),    // 11: clawson.SubscribeReq
	(*StateFrame)(nil),      // 12: clawson.StateFrame
	(*HistoryReq)(nil),      // 13: clawson.HistoryReq
	(*SkillList)(nil),       // 14: clawson.SkillList
	(*ConfigReq)(nil),       // 15: clawson.ConfigReq
	(*SkillListReq)(nil),    // 16: clawson.SkillListReq
	(*SkillNewReq)(nil),     // 17: clawson.SkillNewReq
	(*SkillReadReq)(nil),    // 18: clawson.SkillReadReq
	(*MetricsReq)(nil),      // 19: clawson.MetricsReq
	(*SchedAddReq)(nil),     // 20: clawson.SchedAddReq
	(*SchedListReq)(nil),    // 21: clawson.SchedListReq
	(*SchedIDReq)(nil),      // 22: clawson.SchedIDReq
	(*SchedToggleReq)(nil),  // 23: clawson.SchedToggleReq
	(*BaseResp)(nil),        // 24: clawson.BaseResp
	(*SpawnResp)(nil),       // 25: clawson.SpawnResp
	(*ListResp)(nil),        // 26: clawson.ListResp
	(*HistoryResp)(nil),     // 27: clawson.HistoryResp
	(*ConfigResp)(nil),      // 28: clawson.ConfigResp
	(*MetricsResp)(nil),     // 29: clawson.MetricsResp
	(*SkillsResp)(nil),      // 30: clawson.SkillsResp
	(*SkillNewResp)(nil),    // 31: clawson.SkillNewResp
	(*SkillReadResp)(nil),   // 32: clawson.SkillReadResp
	(*SchedAddResp)(nil),    // 33: clawson.SchedAddResp
	(*SchedListResp)(nil),   // 34: clawson.SchedListResp
	nil,                     // 35: clawson.StateFrame.GroupsEntry
	nil,                     // 36: clawson.ListResp.GroupsEntry
	(*emptypb.Empty)(nil),   // 37: google.protobuf.Empty
	(*structpb.Struct)(nil), // 38: google.protobuf.Struct
}
var file_clawson_proto_depIdxs = []int32{
	35, // 0: clawson.StateFrame.groups:type_name -> clawson.StateFrame.GroupsEntry
	37, // 1: clawson.ConfigReq.skills_clear:type_name -> google.protobuf.Empty
	14, // 2: clawson.ConfigReq.skills_set:type_name -> clawson.SkillList
	36, // 3: clawson.ListResp.groups:type_name -> clawson.ListResp.GroupsEntry
	0,  // 4: clawson.HistoryResp.events:type_name -> clawson.Event
	38, // 5: clawson.ConfigResp.config:type_name -> google.protobuf.Struct
	38, // 6: clawson.MetricsResp.metric:type_name -> google.protobuf.Struct
	38, // 7: clawson.MetricsResp.global_metric:type_name -> google.protobuf.Struct
	3,  // 8: clawson.SkillsResp.skills:type_name -> clawson.SkillItem
	4,  // 9: clawson.SchedAddResp.item:type_name -> clawson.ScheduleItem
	4,  // 10: clawson.SchedListResp.schedules:type_name -> clawson.ScheduleItem
	2,  // 11: clawson.StateFrame.GroupsEntry.value:type_name -> clawson.GroupInfo
	2,  // 12: clawson.ListResp.GroupsEntry.value:type_name -> clawson.GroupInfo
	5,  // 13: clawson.Clawson.Spawn:input_type -> clawson.SpawnReq
	6,  // 14: clawson.Clawson.Send:input_type -> clawson.SendReq
	8,  // 15: clawson.Clawson.List:input_type -> clawson.ListReq
	7,  // 16: clawson.Clawson.Stop:input_type -> clawson.GroupReq
	7,  // 17: clawson.Clawson.Interrupt:input_type -> clawson.GroupReq
	7,  // 18: clawson.Clawson.Destroy:input_type -> clawson.GroupReq
	7,  // 19: clawson.Clawson.Restart:input_type -> clawson.GroupReq
	13, // 20: clawson.Clawson.History:input_type -> clawson.HistoryReq
	15, // 21: clawson.Clawson.Config:input_type -> clawson.ConfigReq
	19, // 22: clawson.Clawson.Metrics:input_type -> clawson.MetricsReq
	7,  // 23: clawson.Clawson.Clear:input_type -> clawson.GroupReq
	16, // 24: clawson.Clawson.Skills:input_type -> clawson.SkillListReq
	17, // 25: clawson.Clawson.SkillNew:input_type -> clawson.SkillNewReq
	18, // 26: clawson.Clawson.SkillRead:input_type -> clawson.SkillReadReq
	20, // 27: clawson.Clawson.SchedAdd:input_type -> clawson.SchedAddReq
	21, // 28: clawson.Clawson.SchedList:input_type -> clawson.SchedListReq
	22, // 29: clawson.Clawson.SchedDel:input_type -> clawson.SchedIDReq
	23, // 30: clawson.Clawson.SchedToggle:input_type -> clawson.SchedToggleReq
	22, // 31: clawson.Clawson.SchedRun:input_type -> clawson.SchedIDReq
	11, // 32: clawson.Clawson.SubscribeGroup:input_type -> clawson.SubscribeReq
	9,  // 33: clawson.Clawson.SubscribeLogs:input_type -> clawson.LogsReq
	10, // 34: clawson.Clawson.WatchState:input_type -> clawson.WatchReq
	25, // 35: clawson.Clawson.Spawn:output_type -> clawson.SpawnResp
	24, // 36: clawson.Clawson.Send:output_type -> clawson.BaseResp
	26, // 37: clawson.Clawson.List:output_type -> clawson.ListResp
	24, // 38: clawson.Clawson.Stop:output_type -> clawson.BaseResp
	24, // 39: clawson.Clawson.Interrupt:output_type -> clawson.BaseResp
	24, // 40: clawson.Clawson.Destroy:output_type -> clawson.BaseResp
	25, // 41: clawson.Clawson.Restart:output_type -> clawson.SpawnResp
	27, // 42: clawson.Clawson.History:output_type -> clawson.HistoryResp
	28, // 43: clawson.Clawson.Config:output_type -> clawson.ConfigResp
	29, // 44: clawson.Clawson.Metrics:output_type -> clawson.MetricsResp
	24, // 45: clawson.Clawson.Clear:output_type -> clawson.BaseResp
	30, // 46: clawson.Clawson.Skills:output_type -> clawson.SkillsResp
	31, // 47: clawson.Clawson.SkillNew:output_type -> clawson.SkillNewResp
	32, // 48: clawson.Clawson.SkillRead:output_type -> clawson.SkillReadResp
	33, // 49: clawson.Clawson.SchedAdd:output_type -> clawson.SchedAddResp
	34, // 50: clawson.Clawson.SchedList:output_type -> clawson.SchedListResp
	24, // 51: clawson.Clawson.SchedDel:output_type -> clawson.BaseResp
	24, // 52: clawson.Clawson.SchedToggle:output_type -> clawson.BaseResp
	24, // 53: clawson.Clawson.SchedRun:output_type -> clawson.BaseResp
	0,  // 54: clawson.Clawson.SubscribeGroup:output_type -> clawson.Event
	1,  // 55: clawson.Clawson.SubscribeLogs:output_type -> clawson.LogEvent
	12, // 56: clawson.Clawson.WatchState:output_type -> clawson.StateFrame
	35, // [35:57] is the sub-list for method output_type
	13, // [13:35] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_clawson_proto_init() }
func file_clawson_proto_init() {
	if File_clawson_proto != nil {
		return
	}
	file_clawson_proto_msgTypes[15].OneofWrappers = []any{
		(*ConfigReq_SkillsClear)(nil),
		(*ConfigReq_SkillsSet)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clawson_proto_rawDesc), len(file_clawson_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clawson_proto_goTypes,
		DependencyIndexes: file_clawson_proto_depIdxs,
		MessageInfos:      file_clawson_proto_msgTypes,
	}.Build()
	File_clawson_proto = out.File
	file_clawson_proto_goTypes = nil
	file_clawson_proto_depIdxs = nil
}
