// Daemon <-> microVM guest wire contract (vsock). Shared by the daemon
// (daemon/fc.go, daemon/ctlpb.go) and the guest PID-1 agent (fcguest/), both
// Go; generated code lands in ./pb next to koto.proto's. Nothing else speaks
// this protocol — it never leaves the host↔guest vsock pair.
//
// Framing on every channel: one uint32 big-endian length prefix + one
// serialized message; each side enforces a per-channel maximum BEFORE
// allocating (daemon/fcframe.go, fcguest/frame.go). Ports (single vsock
// device, demuxed by port — see docs/firecracker-vsock.md):
//
//   guest → host 9002  CtlRequest / CtlResponse   the in-guest control plane
//   host → guest 10000 AgentRequest / AgentResponse, then per-op streams
//                      framed as AgentFrame (run_script, shell_attach) or raw
//                      bytes (exec_stream — a plain pipe the host closes)
//
// 9000 (API egress → proxy) and 9003 (L3 frames → gVisor) are byte pipes with
// their own protocols (HTTP, ethernet) and are not described here; 9001 (log
// stream) is still the [[marker]] text stream — moving it to typed frames is
// the next step.
//
// Why protobuf here, not JSON lines: length-prefixed frames bound every read
// before it allocates; a `oneof` per verb makes the verb set closed and every
// field typed at decode (an unknown or mistyped field is a decode error, not
// a silently-zeroed struct); binary payloads (job output, report bodies) ride
// as `bytes` instead of base64-in-a-string. Request fields keep the JSON
// names the guest-side shell tools (cs-job, cs-notify) already write — the
// guest agent converts their JSON line into a CtlRequest with strict
// protojson, so a malformed line is refused in the guest and never reaches
// the daemon.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: guest.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CtlSendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Session       string                 `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	Reply         bool                   `protobuf:"varint,4,opt,name=reply,proto3" json:"reply,omitempty"`                               // arm a one-shot report window (report.go)
	FromSession   string                 `protobuf:"bytes,5,opt,name=from_session,json=fromSession,proto3" json:"from_session,omitempty"` // main's session that receives the report
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlSendReq) Reset() {
	*x = CtlSendReq{}
	mi := &file_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlSendReq) ProtoMessage() {}

func (x *CtlSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlSendReq.ProtoReflect.Descriptor instead.
func (*CtlSendReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{0}
}

func (x *CtlSendReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CtlSendReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CtlSendReq) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *CtlSendReq) GetReply() bool {
	if x != nil {
		return x.Reply
	}
	return false
}

func (x *CtlSendReq) GetFromSession() string {
	if x != nil {
		return x.FromSession
	}
	return ""
}

type CtlTailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	N             int32                  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlTailReq) Reset() {
	*x = CtlTailReq{}
	mi := &file_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlTailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlTailReq) ProtoMessage() {}

func (x *CtlTailReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlTailReq.ProtoReflect.Descriptor instead.
func (*CtlTailReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{1}
}

func (x *CtlTailReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CtlTailReq) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type JobDoneReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rc            string                 `protobuf:"bytes,2,opt,name=rc,proto3" json:"rc,omitempty"`
	Out           []byte                 `protobuf:"bytes,3,opt,name=out,proto3" json:"out,omitempty"` // trailing bytes of the job's output
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Session       string                 `protobuf:"bytes,5,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDoneReq) Reset() {
	*x = JobDoneReq{}
	mi := &file_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDoneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDoneReq) ProtoMessage() {}

func (x *JobDoneReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDoneReq.ProtoReflect.Descriptor instead.
func (*JobDoneReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{2}
}

func (x *JobDoneReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobDoneReq) GetRc() string {
	if x != nil {
		return x.Rc
	}
	return ""
}

func (x *JobDoneReq) GetOut() []byte {
	if x != nil {
		return x.Out
	}
	return nil
}

func (x *JobDoneReq) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *JobDoneReq) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type NotifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"` // normal | high
	Title         []byte                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Msg           []byte                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Session       string                 `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyReq) Reset() {
	*x = NotifyReq{}
	mi := &file_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReq) ProtoMessage() {}

func (x *NotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReq.ProtoReflect.Descriptor instead.
func (*NotifyReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyReq) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *NotifyReq) GetTitle() []byte {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *NotifyReq) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *NotifyReq) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type ReportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           []byte                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportReq) Reset() {
	*x = ReportReq{}
	mi := &file_guest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportReq) ProtoMessage() {}

func (x *ReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportReq.ProtoReflect.Descriptor instead.
func (*ReportReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{4}
}

func (x *ReportReq) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type GoalDoneReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Note          []byte                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalDoneReq) Reset() {
	*x = GoalDoneReq{}
	mi := &file_guest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalDoneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalDoneReq) ProtoMessage() {}

func (x *GoalDoneReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalDoneReq.ProtoReflect.Descriptor instead.
func (*GoalDoneReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{5}
}

func (x *GoalDoneReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GoalDoneReq) GetNote() []byte {
	if x != nil {
		return x.Note
	}
	return nil
}

type GoalVerdictReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Met           bool                   `protobuf:"varint,2,opt,name=met,proto3" json:"met,omitempty"`
	Reasons       []byte                 `protobuf:"bytes,3,opt,name=reasons,proto3" json:"reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalVerdictReq) Reset() {
	*x = GoalVerdictReq{}
	mi := &file_guest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalVerdictReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalVerdictReq) ProtoMessage() {}

func (x *GoalVerdictReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalVerdictReq.ProtoReflect.Descriptor instead.
func (*GoalVerdictReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{6}
}

func (x *GoalVerdictReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GoalVerdictReq) GetMet() bool {
	if x != nil {
		return x.Met
	}
	return false
}

func (x *GoalVerdictReq) GetReasons() []byte {
	if x != nil {
		return x.Reasons
	}
	return nil
}

type CtlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*CtlRequest_Spawn
	//	*CtlRequest_Send
	//	*CtlRequest_Stop
	//	*CtlRequest_List
	//	*CtlRequest_Resources
	//	*CtlRequest_ConfigSet
	//	*CtlRequest_Tail
	//	*CtlRequest_JobDone
	//	*CtlRequest_Notify
	//	*CtlRequest_Report
	//	*CtlRequest_GoalDone
	//	*CtlRequest_GoalVerdict
	//	*CtlRequest_GoalSet
	//	*CtlRequest_GoalApprove
	//	*CtlRequest_GoalStatus
	//	*CtlRequest_GoalPause
	//	*CtlRequest_GoalInterrupt
	//	*CtlRequest_GoalResume
	//	*CtlRequest_GoalCancel
	//	*CtlRequest_SchedAdd
	//	*CtlRequest_SchedList
	//	*CtlRequest_SchedDel
	//	*CtlRequest_SchedToggle
	//	*CtlRequest_SchedRun
	Cmd           isCtlRequest_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlRequest) Reset() {
	*x = CtlRequest{}
	mi := &file_guest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlRequest) ProtoMessage() {}

func (x *CtlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlRequest.ProtoReflect.Descriptor instead.
func (*CtlRequest) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{7}
}

func (x *CtlRequest) GetCmd() isCtlRequest_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *CtlRequest) GetSpawn() *SpawnReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_Spawn); ok {
			return x.Spawn
		}
	}
	return nil
}

func (x *CtlRequest) GetSend() *CtlSendReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *CtlRequest) GetStop() *GroupReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *CtlRequest) GetList() *ListReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *CtlRequest) GetResources() *ResourcesReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_Resources); ok {
			return x.Resources
		}
	}
	return nil
}

func (x *CtlRequest) GetConfigSet() *ConfigReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_ConfigSet); ok {
			return x.ConfigSet
		}
	}
	return nil
}

func (x *CtlRequest) GetTail() *CtlTailReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_Tail); ok {
			return x.Tail
		}
	}
	return nil
}

func (x *CtlRequest) GetJobDone() *JobDoneReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_JobDone); ok {
			return x.JobDone
		}
	}
	return nil
}

func (x *CtlRequest) GetNotify() *NotifyReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_Notify); ok {
			return x.Notify
		}
	}
	return nil
}

func (x *CtlRequest) GetReport() *ReportReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_Report); ok {
			return x.Report
		}
	}
	return nil
}

func (x *CtlRequest) GetGoalDone() *GoalDoneReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_GoalDone); ok {
			return x.GoalDone
		}
	}
	return nil
}

func (x *CtlRequest) GetGoalVerdict() *GoalVerdictReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_GoalVerdict); ok {
			return x.GoalVerdict
		}
	}
	return nil
}

func (x *CtlRequest) GetGoalSet() *GoalSetReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_GoalSet); ok {
			return x.GoalSet
		}
	}
	return nil
}

func (x *CtlRequest) GetGoalApprove() *GoalGroupReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_GoalApprove); ok {
			return x.GoalApprove
		}
	}
	return nil
}

func (x *CtlRequest) GetGoalStatus() *GoalListReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_GoalStatus); ok {
			return x.GoalStatus
		}
	}
	return nil
}

func (x *CtlRequest) GetGoalPause() *GoalGroupReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_GoalPause); ok {
			return x.GoalPause
		}
	}
	return nil
}

func (x *CtlRequest) GetGoalInterrupt() *GoalGroupReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_GoalInterrupt); ok {
			return x.GoalInterrupt
		}
	}
	return nil
}

func (x *CtlRequest) GetGoalResume() *GoalGroupReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_GoalResume); ok {
			return x.GoalResume
		}
	}
	return nil
}

func (x *CtlRequest) GetGoalCancel() *GoalGroupReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_GoalCancel); ok {
			return x.GoalCancel
		}
	}
	return nil
}

func (x *CtlRequest) GetSchedAdd() *SchedAddReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_SchedAdd); ok {
			return x.SchedAdd
		}
	}
	return nil
}

func (x *CtlRequest) GetSchedList() *SchedListReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_SchedList); ok {
			return x.SchedList
		}
	}
	return nil
}

func (x *CtlRequest) GetSchedDel() *SchedIDReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_SchedDel); ok {
			return x.SchedDel
		}
	}
	return nil
}

func (x *CtlRequest) GetSchedToggle() *SchedToggleReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_SchedToggle); ok {
			return x.SchedToggle
		}
	}
	return nil
}

func (x *CtlRequest) GetSchedRun() *SchedIDReq {
	if x != nil {
		if x, ok := x.Cmd.(*CtlRequest_SchedRun); ok {
			return x.SchedRun
		}
	}
	return nil
}

type isCtlRequest_Cmd interface {
	isCtlRequest_Cmd()
}

type CtlRequest_Spawn struct {
	Spawn *SpawnReq `protobuf:"bytes,1,opt,name=spawn,proto3,oneof"`
}

type CtlRequest_Send struct {
	Send *CtlSendReq `protobuf:"bytes,2,opt,name=send,proto3,oneof"`
}

type CtlRequest_Stop struct {
	Stop *GroupReq `protobuf:"bytes,3,opt,name=stop,proto3,oneof"`
}

type CtlRequest_List struct {
	List *ListReq `protobuf:"bytes,4,opt,name=list,proto3,oneof"`
}

type CtlRequest_Resources struct {
	Resources *ResourcesReq `protobuf:"bytes,5,opt,name=resources,proto3,oneof"`
}

type CtlRequest_ConfigSet struct {
	ConfigSet *ConfigReq `protobuf:"bytes,6,opt,name=config_set,json=configSet,proto3,oneof"`
}

type CtlRequest_Tail struct {
	Tail *CtlTailReq `protobuf:"bytes,7,opt,name=tail,proto3,oneof"`
}

type CtlRequest_JobDone struct {
	JobDone *JobDoneReq `protobuf:"bytes,8,opt,name=job_done,json=jobDone,proto3,oneof"`
}

type CtlRequest_Notify struct {
	Notify *NotifyReq `protobuf:"bytes,9,opt,name=notify,proto3,oneof"`
}

type CtlRequest_Report struct {
	Report *ReportReq `protobuf:"bytes,10,opt,name=report,proto3,oneof"`
}

type CtlRequest_GoalDone struct {
	GoalDone *GoalDoneReq `protobuf:"bytes,11,opt,name=goal_done,json=goalDone,proto3,oneof"`
}

type CtlRequest_GoalVerdict struct {
	GoalVerdict *GoalVerdictReq `protobuf:"bytes,12,opt,name=goal_verdict,json=goalVerdict,proto3,oneof"`
}

type CtlRequest_GoalSet struct {
	GoalSet *GoalSetReq `protobuf:"bytes,13,opt,name=goal_set,json=goalSet,proto3,oneof"`
}

type CtlRequest_GoalApprove struct {
	GoalApprove *GoalGroupReq `protobuf:"bytes,14,opt,name=goal_approve,json=goalApprove,proto3,oneof"`
}

type CtlRequest_GoalStatus struct {
	GoalStatus *GoalListReq `protobuf:"bytes,15,opt,name=goal_status,json=goalStatus,proto3,oneof"`
}

type CtlRequest_GoalPause struct {
	GoalPause *GoalGroupReq `protobuf:"bytes,16,opt,name=goal_pause,json=goalPause,proto3,oneof"`
}

type CtlRequest_GoalInterrupt struct {
	GoalInterrupt *GoalGroupReq `protobuf:"bytes,17,opt,name=goal_interrupt,json=goalInterrupt,proto3,oneof"`
}

type CtlRequest_GoalResume struct {
	GoalResume *GoalGroupReq `protobuf:"bytes,18,opt,name=goal_resume,json=goalResume,proto3,oneof"`
}

type CtlRequest_GoalCancel struct {
	GoalCancel *GoalGroupReq `protobuf:"bytes,19,opt,name=goal_cancel,json=goalCancel,proto3,oneof"`
}

type CtlRequest_SchedAdd struct {
	SchedAdd *SchedAddReq `protobuf:"bytes,20,opt,name=sched_add,json=schedAdd,proto3,oneof"`
}

type CtlRequest_SchedList struct {
	SchedList *SchedListReq `protobuf:"bytes,21,opt,name=sched_list,json=schedList,proto3,oneof"`
}

type CtlRequest_SchedDel struct {
	SchedDel *SchedIDReq `protobuf:"bytes,22,opt,name=sched_del,json=schedDel,proto3,oneof"`
}

type CtlRequest_SchedToggle struct {
	SchedToggle *SchedToggleReq `protobuf:"bytes,23,opt,name=sched_toggle,json=schedToggle,proto3,oneof"`
}

type CtlRequest_SchedRun struct {
	SchedRun *SchedIDReq `protobuf:"bytes,24,opt,name=sched_run,json=schedRun,proto3,oneof"`
}

func (*CtlRequest_Spawn) isCtlRequest_Cmd() {}

func (*CtlRequest_Send) isCtlRequest_Cmd() {}

func (*CtlRequest_Stop) isCtlRequest_Cmd() {}

func (*CtlRequest_List) isCtlRequest_Cmd() {}

func (*CtlRequest_Resources) isCtlRequest_Cmd() {}

func (*CtlRequest_ConfigSet) isCtlRequest_Cmd() {}

func (*CtlRequest_Tail) isCtlRequest_Cmd() {}

func (*CtlRequest_JobDone) isCtlRequest_Cmd() {}

func (*CtlRequest_Notify) isCtlRequest_Cmd() {}

func (*CtlRequest_Report) isCtlRequest_Cmd() {}

func (*CtlRequest_GoalDone) isCtlRequest_Cmd() {}

func (*CtlRequest_GoalVerdict) isCtlRequest_Cmd() {}

func (*CtlRequest_GoalSet) isCtlRequest_Cmd() {}

func (*CtlRequest_GoalApprove) isCtlRequest_Cmd() {}

func (*CtlRequest_GoalStatus) isCtlRequest_Cmd() {}

func (*CtlRequest_GoalPause) isCtlRequest_Cmd() {}

func (*CtlRequest_GoalInterrupt) isCtlRequest_Cmd() {}

func (*CtlRequest_GoalResume) isCtlRequest_Cmd() {}

func (*CtlRequest_GoalCancel) isCtlRequest_Cmd() {}

func (*CtlRequest_SchedAdd) isCtlRequest_Cmd() {}

func (*CtlRequest_SchedList) isCtlRequest_Cmd() {}

func (*CtlRequest_SchedDel) isCtlRequest_Cmd() {}

func (*CtlRequest_SchedToggle) isCtlRequest_Cmd() {}

func (*CtlRequest_SchedRun) isCtlRequest_Cmd() {}

type CtlTailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlTailResp) Reset() {
	*x = CtlTailResp{}
	mi := &file_guest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlTailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlTailResp) ProtoMessage() {}

func (x *CtlTailResp) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlTailResp.ProtoReflect.Descriptor instead.
func (*CtlTailResp) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{8}
}

func (x *CtlTailResp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ok/error are the envelope; `result` carries the verb's payload. The guest
// agent flattens the payload into the top-level JSON object it appends to
// .cs/ctl.out, so the shape agents read is unchanged ({"ok":true,"port":..}).
type CtlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*CtlResponse_Port
	//	*CtlResponse_List
	//	*CtlResponse_Resources
	//	*CtlResponse_Config
	//	*CtlResponse_Tail
	//	*CtlResponse_Goal
	//	*CtlResponse_Goals
	//	*CtlResponse_Sched
	//	*CtlResponse_Scheds
	Result        isCtlResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlResponse) Reset() {
	*x = CtlResponse{}
	mi := &file_guest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlResponse) ProtoMessage() {}

func (x *CtlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlResponse.ProtoReflect.Descriptor instead.
func (*CtlResponse) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{9}
}

func (x *CtlResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CtlResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CtlResponse) GetResult() isCtlResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CtlResponse) GetPort() int32 {
	if x != nil {
		if x, ok := x.Result.(*CtlResponse_Port); ok {
			return x.Port
		}
	}
	return 0
}

func (x *CtlResponse) GetList() *ListResp {
	if x != nil {
		if x, ok := x.Result.(*CtlResponse_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *CtlResponse) GetResources() *ResourcesResp {
	if x != nil {
		if x, ok := x.Result.(*CtlResponse_Resources); ok {
			return x.Resources
		}
	}
	return nil
}

func (x *CtlResponse) GetConfig() *ConfigResp {
	if x != nil {
		if x, ok := x.Result.(*CtlResponse_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *CtlResponse) GetTail() *CtlTailResp {
	if x != nil {
		if x, ok := x.Result.(*CtlResponse_Tail); ok {
			return x.Tail
		}
	}
	return nil
}

func (x *CtlResponse) GetGoal() *GoalResp {
	if x != nil {
		if x, ok := x.Result.(*CtlResponse_Goal); ok {
			return x.Goal
		}
	}
	return nil
}

func (x *CtlResponse) GetGoals() *GoalListResp {
	if x != nil {
		if x, ok := x.Result.(*CtlResponse_Goals); ok {
			return x.Goals
		}
	}
	return nil
}

func (x *CtlResponse) GetSched() *SchedAddResp {
	if x != nil {
		if x, ok := x.Result.(*CtlResponse_Sched); ok {
			return x.Sched
		}
	}
	return nil
}

func (x *CtlResponse) GetScheds() *SchedListResp {
	if x != nil {
		if x, ok := x.Result.(*CtlResponse_Scheds); ok {
			return x.Scheds
		}
	}
	return nil
}

type isCtlResponse_Result interface {
	isCtlResponse_Result()
}

type CtlResponse_Port struct {
	Port int32 `protobuf:"varint,3,opt,name=port,proto3,oneof"` // spawn
}

type CtlResponse_List struct {
	List *ListResp `protobuf:"bytes,4,opt,name=list,proto3,oneof"`
}

type CtlResponse_Resources struct {
	Resources *ResourcesResp `protobuf:"bytes,5,opt,name=resources,proto3,oneof"`
}

type CtlResponse_Config struct {
	Config *ConfigResp `protobuf:"bytes,6,opt,name=config,proto3,oneof"`
}

type CtlResponse_Tail struct {
	Tail *CtlTailResp `protobuf:"bytes,7,opt,name=tail,proto3,oneof"`
}

type CtlResponse_Goal struct {
	Goal *GoalResp `protobuf:"bytes,8,opt,name=goal,proto3,oneof"` // goal_set / approve / pause / interrupt / resume / cancel
}

type CtlResponse_Goals struct {
	Goals *GoalListResp `protobuf:"bytes,9,opt,name=goals,proto3,oneof"` // goal_status
}

type CtlResponse_Sched struct {
	Sched *SchedAddResp `protobuf:"bytes,10,opt,name=sched,proto3,oneof"` // sched_add
}

type CtlResponse_Scheds struct {
	Scheds *SchedListResp `protobuf:"bytes,11,opt,name=scheds,proto3,oneof"` // sched_list
}

func (*CtlResponse_Port) isCtlResponse_Result() {}

func (*CtlResponse_List) isCtlResponse_Result() {}

func (*CtlResponse_Resources) isCtlResponse_Result() {}

func (*CtlResponse_Config) isCtlResponse_Result() {}

func (*CtlResponse_Tail) isCtlResponse_Result() {}

func (*CtlResponse_Goal) isCtlResponse_Result() {}

func (*CtlResponse_Goals) isCtlResponse_Result() {}

func (*CtlResponse_Sched) isCtlResponse_Result() {}

func (*CtlResponse_Scheds) isCtlResponse_Result() {}

type InitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []int32                `protobuf:"varint,1,rep,packed,name=ports,proto3" json:"ports,omitempty"`                                                               // published TCP ports to bridge
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // entrypoint + exec environment
	Net           string                 `protobuf:"bytes,3,opt,name=net,proto3" json:"net,omitempty"`                                                                           // "" | "l3" — bring the TAP up (network ≠ none)
	Root          bool                   `protobuf:"varint,4,opt,name=root,proto3" json:"root,omitempty"`                                                                        // root=yes profile
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`                                                                       // hostname koto-vm-<group>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitReq) Reset() {
	*x = InitReq{}
	mi := &file_guest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitReq) ProtoMessage() {}

func (x *InitReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitReq.ProtoReflect.Descriptor instead.
func (*InitReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{10}
}

func (x *InitReq) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *InitReq) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *InitReq) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

func (x *InitReq) GetRoot() bool {
	if x != nil {
		return x.Root
	}
	return false
}

func (x *InitReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type MsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           []byte                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"` // the turn's message body (raw)
	SystemPrompt  []byte                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	ConfigJson    []byte                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // "" = leave config.json untouched
	UploadsTar    []byte                 `protobuf:"bytes,4,opt,name=uploads_tar,json=uploadsTar,proto3" json:"uploads_tar,omitempty"` // attachments newer than the host watermark
	Session       string                 `protobuf:"bytes,5,opt,name=session,proto3" json:"session,omitempty"`                         // "" = default
	Slot          int32                  `protobuf:"varint,6,opt,name=slot,proto3" json:"slot,omitempty"`                              // which log.<n> stream this turn writes to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgReq) Reset() {
	*x = MsgReq{}
	mi := &file_guest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReq) ProtoMessage() {}

func (x *MsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgReq.ProtoReflect.Descriptor instead.
func (*MsgReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{11}
}

func (x *MsgReq) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MsgReq) GetSystemPrompt() []byte {
	if x != nil {
		return x.SystemPrompt
	}
	return nil
}

func (x *MsgReq) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *MsgReq) GetUploadsTar() []byte {
	if x != nil {
		return x.UploadsTar
	}
	return nil
}

func (x *MsgReq) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *MsgReq) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type ExecReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecReq) Reset() {
	*x = ExecReq{}
	mi := &file_guest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecReq) ProtoMessage() {}

func (x *ExecReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecReq.ProtoReflect.Descriptor instead.
func (*ExecReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{12}
}

func (x *ExecReq) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type ExecStreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStreamReq) Reset() {
	*x = ExecStreamReq{}
	mi := &file_guest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStreamReq) ProtoMessage() {}

func (x *ExecStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStreamReq.ProtoReflect.Descriptor instead.
func (*ExecStreamReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{13}
}

func (x *ExecStreamReq) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type GuestScriptReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestScriptReq) Reset() {
	*x = GuestScriptReq{}
	mi := &file_guest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestScriptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestScriptReq) ProtoMessage() {}

func (x *GuestScriptReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestScriptReq.ProtoReflect.Descriptor instead.
func (*GuestScriptReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{14}
}

func (x *GuestScriptReq) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type ShellAttachReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellAttachReq) Reset() {
	*x = ShellAttachReq{}
	mi := &file_guest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellAttachReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellAttachReq) ProtoMessage() {}

func (x *ShellAttachReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellAttachReq.ProtoReflect.Descriptor instead.
func (*ShellAttachReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{15}
}

func (x *ShellAttachReq) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ShellAttachReq) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ShellAttachReq) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ShutdownReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownReq) Reset() {
	*x = ShutdownReq{}
	mi := &file_guest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownReq) ProtoMessage() {}

func (x *ShutdownReq) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownReq.ProtoReflect.Descriptor instead.
func (*ShutdownReq) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{16}
}

type AgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*AgentRequest_Init
	//	*AgentRequest_Msg
	//	*AgentRequest_Exec
	//	*AgentRequest_ExecStream
	//	*AgentRequest_RunScript
	//	*AgentRequest_ShellAttach
	//	*AgentRequest_Shutdown
	Op            isAgentRequest_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_guest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{17}
}

func (x *AgentRequest) GetOp() isAgentRequest_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *AgentRequest) GetInit() *InitReq {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *AgentRequest) GetMsg() *MsgReq {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_Msg); ok {
			return x.Msg
		}
	}
	return nil
}

func (x *AgentRequest) GetExec() *ExecReq {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *AgentRequest) GetExecStream() *ExecStreamReq {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_ExecStream); ok {
			return x.ExecStream
		}
	}
	return nil
}

func (x *AgentRequest) GetRunScript() *GuestScriptReq {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_RunScript); ok {
			return x.RunScript
		}
	}
	return nil
}

func (x *AgentRequest) GetShellAttach() *ShellAttachReq {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_ShellAttach); ok {
			return x.ShellAttach
		}
	}
	return nil
}

func (x *AgentRequest) GetShutdown() *ShutdownReq {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isAgentRequest_Op interface {
	isAgentRequest_Op()
}

type AgentRequest_Init struct {
	Init *InitReq `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type AgentRequest_Msg struct {
	Msg *MsgReq `protobuf:"bytes,2,opt,name=msg,proto3,oneof"`
}

type AgentRequest_Exec struct {
	Exec *ExecReq `protobuf:"bytes,3,opt,name=exec,proto3,oneof"`
}

type AgentRequest_ExecStream struct {
	ExecStream *ExecStreamReq `protobuf:"bytes,4,opt,name=exec_stream,json=execStream,proto3,oneof"`
}

type AgentRequest_RunScript struct {
	RunScript *GuestScriptReq `protobuf:"bytes,5,opt,name=run_script,json=runScript,proto3,oneof"`
}

type AgentRequest_ShellAttach struct {
	ShellAttach *ShellAttachReq `protobuf:"bytes,6,opt,name=shell_attach,json=shellAttach,proto3,oneof"`
}

type AgentRequest_Shutdown struct {
	Shutdown *ShutdownReq `protobuf:"bytes,7,opt,name=shutdown,proto3,oneof"`
}

func (*AgentRequest_Init) isAgentRequest_Op() {}

func (*AgentRequest_Msg) isAgentRequest_Op() {}

func (*AgentRequest_Exec) isAgentRequest_Op() {}

func (*AgentRequest_ExecStream) isAgentRequest_Op() {}

func (*AgentRequest_RunScript) isAgentRequest_Op() {}

func (*AgentRequest_ShellAttach) isAgentRequest_Op() {}

func (*AgentRequest_Shutdown) isAgentRequest_Op() {}

type AgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Rc            int32                  `protobuf:"varint,3,opt,name=rc,proto3" json:"rc,omitempty"`  // exec
	Out           []byte                 `protobuf:"bytes,4,opt,name=out,proto3" json:"out,omitempty"` // exec: combined stdout+stderr
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_guest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{18}
}

func (x *AgentResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AgentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentResponse) GetRc() int32 {
	if x != nil {
		return x.Rc
	}
	return 0
}

func (x *AgentResponse) GetOut() []byte {
	if x != nil {
		return x.Out
	}
	return nil
}

// Stream frame for run_script (guest→host) and shell_attach (both ways).
// A guest-side close does not surface as a host EOF on hybrid vsock, so
// `end` is the explicit terminator.
type AgentFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*AgentFrame_Data
	//	*AgentFrame_End
	//	*AgentFrame_Error
	//	*AgentFrame_Input
	//	*AgentFrame_Resize
	Kind          isAgentFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFrame) Reset() {
	*x = AgentFrame{}
	mi := &file_guest_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFrame) ProtoMessage() {}

func (x *AgentFrame) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFrame.ProtoReflect.Descriptor instead.
func (*AgentFrame) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{19}
}

func (x *AgentFrame) GetKind() isAgentFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *AgentFrame) GetData() []byte {
	if x != nil {
		if x, ok := x.Kind.(*AgentFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *AgentFrame) GetEnd() bool {
	if x != nil {
		if x, ok := x.Kind.(*AgentFrame_End); ok {
			return x.End
		}
	}
	return false
}

func (x *AgentFrame) GetError() string {
	if x != nil {
		if x, ok := x.Kind.(*AgentFrame_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *AgentFrame) GetInput() []byte {
	if x != nil {
		if x, ok := x.Kind.(*AgentFrame_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *AgentFrame) GetResize() *ShellResize {
	if x != nil {
		if x, ok := x.Kind.(*AgentFrame_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isAgentFrame_Kind interface {
	isAgentFrame_Kind()
}

type AgentFrame_Data struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3,oneof"` // guest→host: output chunk
}

type AgentFrame_End struct {
	End bool `protobuf:"varint,2,opt,name=end,proto3,oneof"` // guest→host: stream done
}

type AgentFrame_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // guest→host: couldn't start / failed
}

type AgentFrame_Input struct {
	Input []byte `protobuf:"bytes,4,opt,name=input,proto3,oneof"` // host→guest (shell): stdin bytes
}

type AgentFrame_Resize struct {
	Resize *ShellResize `protobuf:"bytes,5,opt,name=resize,proto3,oneof"` // host→guest (shell): pty geometry
}

func (*AgentFrame_Data) isAgentFrame_Kind() {}

func (*AgentFrame_End) isAgentFrame_Kind() {}

func (*AgentFrame_Error) isAgentFrame_Kind() {}

func (*AgentFrame_Input) isAgentFrame_Kind() {}

func (*AgentFrame_Resize) isAgentFrame_Kind() {}

// ---- 9004: turn stream (guest → host) --------------------------------------
// One connection per turn: the guest agent dials when it starts the turn's
// worker, sends TurnOpen{slot} first, then the turn's events as they happen,
// and TurnEnd last (always — a timed-out or killed worker still ends its
// turn). The daemon serializes the frames into the slot's host-side log file
// in the [[marker]] text grammar (daemon/logparse.go), so History, the
// tailer and every reader are unchanged — but the guest can no longer author
// a marker: text is bytes, markers are frame types, and the daemon escapes
// any text line that would parse as one. Replaces the raw 9001/9004 byte
// streams (9001 is gone; the guest has no channel that writes raw text into
// a host file).
type TurnOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnOpen) Reset() {
	*x = TurnOpen{}
	mi := &file_guest_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnOpen) ProtoMessage() {}

func (x *TurnOpen) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnOpen.ProtoReflect.Descriptor instead.
func (*TurnOpen) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{20}
}

func (x *TurnOpen) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type ToolUse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUse) Reset() {
	*x = ToolUse{}
	mi := &file_guest_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUse) ProtoMessage() {}

func (x *ToolUse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUse.ProtoReflect.Descriptor instead.
func (*ToolUse) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{21}
}

func (x *ToolUse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolUse) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type TurnFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*TurnFrame_Open
	//	*TurnFrame_Text
	//	*TurnFrame_ThinkBegin
	//	*TurnFrame_ThinkEnd
	//	*TurnFrame_Tool
	//	*TurnFrame_ToolOutBegin
	//	*TurnFrame_ToolOutEnd
	//	*TurnFrame_Err
	//	*TurnFrame_TurnEnd
	Kind          isTurnFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnFrame) Reset() {
	*x = TurnFrame{}
	mi := &file_guest_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnFrame) ProtoMessage() {}

func (x *TurnFrame) ProtoReflect() protoreflect.Message {
	mi := &file_guest_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnFrame.ProtoReflect.Descriptor instead.
func (*TurnFrame) Descriptor() ([]byte, []int) {
	return file_guest_proto_rawDescGZIP(), []int{22}
}

func (x *TurnFrame) GetKind() isTurnFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *TurnFrame) GetOpen() *TurnOpen {
	if x != nil {
		if x, ok := x.Kind.(*TurnFrame_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *TurnFrame) GetText() []byte {
	if x != nil {
		if x, ok := x.Kind.(*TurnFrame_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *TurnFrame) GetThinkBegin() bool {
	if x != nil {
		if x, ok := x.Kind.(*TurnFrame_ThinkBegin); ok {
			return x.ThinkBegin
		}
	}
	return false
}

func (x *TurnFrame) GetThinkEnd() int32 {
	if x != nil {
		if x, ok := x.Kind.(*TurnFrame_ThinkEnd); ok {
			return x.ThinkEnd
		}
	}
	return 0
}

func (x *TurnFrame) GetTool() *ToolUse {
	if x != nil {
		if x, ok := x.Kind.(*TurnFrame_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *TurnFrame) GetToolOutBegin() bool {
	if x != nil {
		if x, ok := x.Kind.(*TurnFrame_ToolOutBegin); ok {
			return x.ToolOutBegin
		}
	}
	return false
}

func (x *TurnFrame) GetToolOutEnd() int64 {
	if x != nil {
		if x, ok := x.Kind.(*TurnFrame_ToolOutEnd); ok {
			return x.ToolOutEnd
		}
	}
	return 0
}

func (x *TurnFrame) GetErr() string {
	if x != nil {
		if x, ok := x.Kind.(*TurnFrame_Err); ok {
			return x.Err
		}
	}
	return ""
}

func (x *TurnFrame) GetTurnEnd() bool {
	if x != nil {
		if x, ok := x.Kind.(*TurnFrame_TurnEnd); ok {
			return x.TurnEnd
		}
	}
	return false
}

type isTurnFrame_Kind interface {
	isTurnFrame_Kind()
}

type TurnFrame_Open struct {
	Open *TurnOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type TurnFrame_Text struct {
	Text []byte `protobuf:"bytes,2,opt,name=text,proto3,oneof"` // response text; think/tool-out body while that block is open
}

type TurnFrame_ThinkBegin struct {
	ThinkBegin bool `protobuf:"varint,3,opt,name=think_begin,json=thinkBegin,proto3,oneof"`
}

type TurnFrame_ThinkEnd struct {
	ThinkEnd int32 `protobuf:"varint,4,opt,name=think_end,json=thinkEnd,proto3,oneof"` // word count
}

type TurnFrame_Tool struct {
	Tool *ToolUse `protobuf:"bytes,5,opt,name=tool,proto3,oneof"`
}

type TurnFrame_ToolOutBegin struct {
	ToolOutBegin bool `protobuf:"varint,6,opt,name=tool_out_begin,json=toolOutBegin,proto3,oneof"`
}

type TurnFrame_ToolOutEnd struct {
	ToolOutEnd int64 `protobuf:"varint,7,opt,name=tool_out_end,json=toolOutEnd,proto3,oneof"` // byte count of the body
}

type TurnFrame_Err struct {
	Err string `protobuf:"bytes,8,opt,name=err,proto3,oneof"` // [[err]] line
}

type TurnFrame_TurnEnd struct {
	TurnEnd bool `protobuf:"varint,9,opt,name=turn_end,json=turnEnd,proto3,oneof"`
}

func (*TurnFrame_Open) isTurnFrame_Kind() {}

func (*TurnFrame_Text) isTurnFrame_Kind() {}

func (*TurnFrame_ThinkBegin) isTurnFrame_Kind() {}

func (*TurnFrame_ThinkEnd) isTurnFrame_Kind() {}

func (*TurnFrame_Tool) isTurnFrame_Kind() {}

func (*TurnFrame_ToolOutBegin) isTurnFrame_Kind() {}

func (*TurnFrame_ToolOutEnd) isTurnFrame_Kind() {}

func (*TurnFrame_Err) isTurnFrame_Kind() {}

func (*TurnFrame_TurnEnd) isTurnFrame_Kind() {}

var File_guest_proto protoreflect.FileDescriptor

const file_guest_proto_rawDesc = "" +
	"\n" +
	"\vguest.proto\x12\x04koto\x1a\n" +
	"koto.proto\"\x87\x01\n" +
	"\n" +
	"CtlSendReq\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x18\n" +
	"\asession\x18\x03 \x01(\tR\asession\x12\x14\n" +
	"\x05reply\x18\x04 \x01(\bR\x05reply\x12!\n" +
	"\ffrom_session\x18\x05 \x01(\tR\vfromSession\"0\n" +
	"\n" +
	"CtlTailReq\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\f\n" +
	"\x01n\x18\x02 \x01(\x05R\x01n\"n\n" +
	"\n" +
	"JobDoneReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02rc\x18\x02 \x01(\tR\x02rc\x12\x10\n" +
	"\x03out\x18\x03 \x01(\fR\x03out\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x18\n" +
	"\asession\x18\x05 \x01(\tR\asession\"i\n" +
	"\tNotifyReq\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x14\n" +
	"\x05title\x18\x02 \x01(\fR\x05title\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\fR\x03msg\x12\x18\n" +
	"\asession\x18\x04 \x01(\tR\asession\"\x1d\n" +
	"\tReportReq\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\fR\x03msg\"1\n" +
	"\vGoalDoneReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04note\x18\x02 \x01(\fR\x04note\"L\n" +
	"\x0eGoalVerdictReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03met\x18\x02 \x01(\bR\x03met\x12\x18\n" +
	"\areasons\x18\x03 \x01(\fR\areasons\"\xb0\t\n" +
	"\n" +
	"CtlRequest\x12&\n" +
	"\x05spawn\x18\x01 \x01(\v2\x0e.koto.SpawnReqH\x00R\x05spawn\x12&\n" +
	"\x04send\x18\x02 \x01(\v2\x10.koto.CtlSendReqH\x00R\x04send\x12$\n" +
	"\x04stop\x18\x03 \x01(\v2\x0e.koto.GroupReqH\x00R\x04stop\x12#\n" +
	"\x04list\x18\x04 \x01(\v2\r.koto.ListReqH\x00R\x04list\x122\n" +
	"\tresources\x18\x05 \x01(\v2\x12.koto.ResourcesReqH\x00R\tresources\x120\n" +
	"\n" +
	"config_set\x18\x06 \x01(\v2\x0f.koto.ConfigReqH\x00R\tconfigSet\x12&\n" +
	"\x04tail\x18\a \x01(\v2\x10.koto.CtlTailReqH\x00R\x04tail\x12-\n" +
	"\bjob_done\x18\b \x01(\v2\x10.koto.JobDoneReqH\x00R\ajobDone\x12)\n" +
	"\x06notify\x18\t \x01(\v2\x0f.koto.NotifyReqH\x00R\x06notify\x12)\n" +
	"\x06report\x18\n" +
	" \x01(\v2\x0f.koto.ReportReqH\x00R\x06report\x120\n" +
	"\tgoal_done\x18\v \x01(\v2\x11.koto.GoalDoneReqH\x00R\bgoalDone\x129\n" +
	"\fgoal_verdict\x18\f \x01(\v2\x14.koto.GoalVerdictReqH\x00R\vgoalVerdict\x12-\n" +
	"\bgoal_set\x18\r \x01(\v2\x10.koto.GoalSetReqH\x00R\agoalSet\x127\n" +
	"\fgoal_approve\x18\x0e \x01(\v2\x12.koto.GoalGroupReqH\x00R\vgoalApprove\x124\n" +
	"\vgoal_status\x18\x0f \x01(\v2\x11.koto.GoalListReqH\x00R\n" +
	"goalStatus\x123\n" +
	"\n" +
	"goal_pause\x18\x10 \x01(\v2\x12.koto.GoalGroupReqH\x00R\tgoalPause\x12;\n" +
	"\x0egoal_interrupt\x18\x11 \x01(\v2\x12.koto.GoalGroupReqH\x00R\rgoalInterrupt\x125\n" +
	"\vgoal_resume\x18\x12 \x01(\v2\x12.koto.GoalGroupReqH\x00R\n" +
	"goalResume\x125\n" +
	"\vgoal_cancel\x18\x13 \x01(\v2\x12.koto.GoalGroupReqH\x00R\n" +
	"goalCancel\x120\n" +
	"\tsched_add\x18\x14 \x01(\v2\x11.koto.SchedAddReqH\x00R\bschedAdd\x123\n" +
	"\n" +
	"sched_list\x18\x15 \x01(\v2\x12.koto.SchedListReqH\x00R\tschedList\x12/\n" +
	"\tsched_del\x18\x16 \x01(\v2\x10.koto.SchedIDReqH\x00R\bschedDel\x129\n" +
	"\fsched_toggle\x18\x17 \x01(\v2\x14.koto.SchedToggleReqH\x00R\vschedToggle\x12/\n" +
	"\tsched_run\x18\x18 \x01(\v2\x10.koto.SchedIDReqH\x00R\bschedRunB\x05\n" +
	"\x03cmd\"!\n" +
	"\vCtlTailResp\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xb0\x03\n" +
	"\vCtlResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x04port\x18\x03 \x01(\x05H\x00R\x04port\x12$\n" +
	"\x04list\x18\x04 \x01(\v2\x0e.koto.ListRespH\x00R\x04list\x123\n" +
	"\tresources\x18\x05 \x01(\v2\x13.koto.ResourcesRespH\x00R\tresources\x12*\n" +
	"\x06config\x18\x06 \x01(\v2\x10.koto.ConfigRespH\x00R\x06config\x12'\n" +
	"\x04tail\x18\a \x01(\v2\x11.koto.CtlTailRespH\x00R\x04tail\x12$\n" +
	"\x04goal\x18\b \x01(\v2\x0e.koto.GoalRespH\x00R\x04goal\x12*\n" +
	"\x05goals\x18\t \x01(\v2\x12.koto.GoalListRespH\x00R\x05goals\x12*\n" +
	"\x05sched\x18\n" +
	" \x01(\v2\x12.koto.SchedAddRespH\x00R\x05sched\x12-\n" +
	"\x06scheds\x18\v \x01(\v2\x13.koto.SchedListRespH\x00R\x06schedsB\b\n" +
	"\x06result\"\xbd\x01\n" +
	"\aInitReq\x12\x14\n" +
	"\x05ports\x18\x01 \x03(\x05R\x05ports\x12(\n" +
	"\x03env\x18\x02 \x03(\v2\x16.koto.InitReq.EnvEntryR\x03env\x12\x10\n" +
	"\x03net\x18\x03 \x01(\tR\x03net\x12\x12\n" +
	"\x04root\x18\x04 \x01(\bR\x04root\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\x06MsgReq\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\fR\x03msg\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\fR\fsystemPrompt\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\fR\n" +
	"configJson\x12\x1f\n" +
	"\vuploads_tar\x18\x04 \x01(\fR\n" +
	"uploadsTar\x12\x18\n" +
	"\asession\x18\x05 \x01(\tR\asession\x12\x12\n" +
	"\x04slot\x18\x06 \x01(\x05R\x04slot\"!\n" +
	"\aExecReq\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\"'\n" +
	"\rExecStreamReq\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\"(\n" +
	"\x0eGuestScriptReq\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\"R\n" +
	"\x0eShellAttachReq\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\"\r\n" +
	"\vShutdownReq\"\xdb\x02\n" +
	"\fAgentRequest\x12#\n" +
	"\x04init\x18\x01 \x01(\v2\r.koto.InitReqH\x00R\x04init\x12 \n" +
	"\x03msg\x18\x02 \x01(\v2\f.koto.MsgReqH\x00R\x03msg\x12#\n" +
	"\x04exec\x18\x03 \x01(\v2\r.koto.ExecReqH\x00R\x04exec\x126\n" +
	"\vexec_stream\x18\x04 \x01(\v2\x13.koto.ExecStreamReqH\x00R\n" +
	"execStream\x125\n" +
	"\n" +
	"run_script\x18\x05 \x01(\v2\x14.koto.GuestScriptReqH\x00R\trunScript\x129\n" +
	"\fshell_attach\x18\x06 \x01(\v2\x14.koto.ShellAttachReqH\x00R\vshellAttach\x12/\n" +
	"\bshutdown\x18\a \x01(\v2\x11.koto.ShutdownReqH\x00R\bshutdownB\x04\n" +
	"\x02op\"W\n" +
	"\rAgentResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x0e\n" +
	"\x02rc\x18\x03 \x01(\x05R\x02rc\x12\x10\n" +
	"\x03out\x18\x04 \x01(\fR\x03out\"\x9b\x01\n" +
	"\n" +
	"AgentFrame\x12\x14\n" +
	"\x04data\x18\x01 \x01(\fH\x00R\x04data\x12\x12\n" +
	"\x03end\x18\x02 \x01(\bH\x00R\x03end\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x12\x16\n" +
	"\x05input\x18\x04 \x01(\fH\x00R\x05input\x12+\n" +
	"\x06resize\x18\x05 \x01(\v2\x11.koto.ShellResizeH\x00R\x06resizeB\x06\n" +
	"\x04kind\"\x1e\n" +
	"\bTurnOpen\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\"3\n" +
	"\aToolUse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\"\xb3\x02\n" +
	"\tTurnFrame\x12$\n" +
	"\x04open\x18\x01 \x01(\v2\x0e.koto.TurnOpenH\x00R\x04open\x12\x14\n" +
	"\x04text\x18\x02 \x01(\fH\x00R\x04text\x12!\n" +
	"\vthink_begin\x18\x03 \x01(\bH\x00R\n" +
	"thinkBegin\x12\x1d\n" +
	"\tthink_end\x18\x04 \x01(\x05H\x00R\bthinkEnd\x12#\n" +
	"\x04tool\x18\x05 \x01(\v2\r.koto.ToolUseH\x00R\x04tool\x12&\n" +
	"\x0etool_out_begin\x18\x06 \x01(\bH\x00R\ftoolOutBegin\x12\"\n" +
	"\ftool_out_end\x18\a \x01(\x03H\x00R\n" +
	"toolOutEnd\x12\x12\n" +
	"\x03err\x18\b \x01(\tH\x00R\x03err\x12\x1b\n" +
	"\bturn_end\x18\t \x01(\bH\x00R\aturnEndB\x06\n" +
	"\x04kindB\x15Z\x13koto-protocol/pb;pbb\x06proto3"

var (
	file_guest_proto_rawDescOnce sync.Once
	file_guest_proto_rawDescData []byte
)

func file_guest_proto_rawDescGZIP() []byte {
	file_guest_proto_rawDescOnce.Do(func() {
		file_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guest_proto_rawDesc), len(file_guest_proto_rawDesc)))
	})
	return file_guest_proto_rawDescData
}

var file_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_guest_proto_goTypes = []any{
	(*CtlSendReq)(nil),     // 0: koto.CtlSendReq
	(*CtlTailReq)(nil),     // 1: koto.CtlTailReq
	(*JobDoneReq)(nil),     // 2: koto.JobDoneReq
	(*NotifyReq)(nil),      // 3: koto.NotifyReq
	(*ReportReq)(nil),      // 4: koto.ReportReq
	(*GoalDoneReq)(nil),    // 5: koto.GoalDoneReq
	(*GoalVerdictReq)(nil), // 6: koto.GoalVerdictReq
	(*CtlRequest)(nil),     // 7: koto.CtlRequest
	(*CtlTailResp)(nil),    // 8: koto.CtlTailResp
	(*CtlResponse)(nil),    // 9: koto.CtlResponse
	(*InitReq)(nil),        // 10: koto.InitReq
	(*MsgReq)(nil),         // 11: koto.MsgReq
	(*ExecReq)(nil),        // 12: koto.ExecReq
	(*ExecStreamReq)(nil),  // 13: koto.ExecStreamReq
	(*GuestScriptReq)(nil), // 14: koto.GuestScriptReq
	(*ShellAttachReq)(nil), // 15: koto.ShellAttachReq
	(*ShutdownReq)(nil),    // 16: koto.ShutdownReq
	(*AgentRequest)(nil),   // 17: koto.AgentRequest
	(*AgentResponse)(nil),  // 18: koto.AgentResponse
	(*AgentFrame)(nil),     // 19: koto.AgentFrame
	(*TurnOpen)(nil),       // 20: koto.TurnOpen
	(*ToolUse)(nil),        // 21: koto.ToolUse
	(*TurnFrame)(nil),      // 22: koto.TurnFrame
	nil,                    // 23: koto.InitReq.EnvEntry
	(*SpawnReq)(nil),       // 24: koto.SpawnReq
	(*GroupReq)(nil),       // 25: koto.GroupReq
	(*ListReq)(nil),        // 26: koto.ListReq
	(*ResourcesReq)(nil),   // 27: koto.ResourcesReq
	(*ConfigReq)(nil),      // 28: koto.ConfigReq
	(*GoalSetReq)(nil),     // 29: koto.GoalSetReq
	(*GoalGroupReq)(nil),   // 30: koto.GoalGroupReq
	(*GoalListReq)(nil),    // 31: koto.GoalListReq
	(*SchedAddReq)(nil),    // 32: koto.SchedAddReq
	(*SchedListReq)(nil),   // 33: koto.SchedListReq
	(*SchedIDReq)(nil),     // 34: koto.SchedIDReq
	(*SchedToggleReq)(nil), // 35: koto.SchedToggleReq
	(*ListResp)(nil),       // 36: koto.ListResp
	(*ResourcesResp)(nil),  // 37: koto.ResourcesResp
	(*ConfigResp)(nil),     // 38: koto.ConfigResp
	(*GoalResp)(nil),       // 39: koto.GoalResp
	(*GoalListResp)(nil),   // 40: koto.GoalListResp
	(*SchedAddResp)(nil),   // 41: koto.SchedAddResp
	(*SchedListResp)(nil),  // 42: koto.SchedListResp
	(*ShellResize)(nil),    // 43: koto.ShellResize
}
var file_guest_proto_depIdxs = []int32{
	24, // 0: koto.CtlRequest.spawn:type_name -> koto.SpawnReq
	0,  // 1: koto.CtlRequest.send:type_name -> koto.CtlSendReq
	25, // 2: koto.CtlRequest.stop:type_name -> koto.GroupReq
	26, // 3: koto.CtlRequest.list:type_name -> koto.ListReq
	27, // 4: koto.CtlRequest.resources:type_name -> koto.ResourcesReq
	28, // 5: koto.CtlRequest.config_set:type_name -> koto.ConfigReq
	1,  // 6: koto.CtlRequest.tail:type_name -> koto.CtlTailReq
	2,  // 7: koto.CtlRequest.job_done:type_name -> koto.JobDoneReq
	3,  // 8: koto.CtlRequest.notify:type_name -> koto.NotifyReq
	4,  // 9: koto.CtlRequest.report:type_name -> koto.ReportReq
	5,  // 10: koto.CtlRequest.goal_done:type_name -> koto.GoalDoneReq
	6,  // 11: koto.CtlRequest.goal_verdict:type_name -> koto.GoalVerdictReq
	29, // 12: koto.CtlRequest.goal_set:type_name -> koto.GoalSetReq
	30, // 13: koto.CtlRequest.goal_approve:type_name -> koto.GoalGroupReq
	31, // 14: koto.CtlRequest.goal_status:type_name -> koto.GoalListReq
	30, // 15: koto.CtlRequest.goal_pause:type_name -> koto.GoalGroupReq
	30, // 16: koto.CtlRequest.goal_interrupt:type_name -> koto.GoalGroupReq
	30, // 17: koto.CtlRequest.goal_resume:type_name -> koto.GoalGroupReq
	30, // 18: koto.CtlRequest.goal_cancel:type_name -> koto.GoalGroupReq
	32, // 19: koto.CtlRequest.sched_add:type_name -> koto.SchedAddReq
	33, // 20: koto.CtlRequest.sched_list:type_name -> koto.SchedListReq
	34, // 21: koto.CtlRequest.sched_del:type_name -> koto.SchedIDReq
	35, // 22: koto.CtlRequest.sched_toggle:type_name -> koto.SchedToggleReq
	34, // 23: koto.CtlRequest.sched_run:type_name -> koto.SchedIDReq
	36, // 24: koto.CtlResponse.list:type_name -> koto.ListResp
	37, // 25: koto.CtlResponse.resources:type_name -> koto.ResourcesResp
	38, // 26: koto.CtlResponse.config:type_name -> koto.ConfigResp
	8,  // 27: koto.CtlResponse.tail:type_name -> koto.CtlTailResp
	39, // 28: koto.CtlResponse.goal:type_name -> koto.GoalResp
	40, // 29: koto.CtlResponse.goals:type_name -> koto.GoalListResp
	41, // 30: koto.CtlResponse.sched:type_name -> koto.SchedAddResp
	42, // 31: koto.CtlResponse.scheds:type_name -> koto.SchedListResp
	23, // 32: koto.InitReq.env:type_name -> koto.InitReq.EnvEntry
	10, // 33: koto.AgentRequest.init:type_name -> koto.InitReq
	11, // 34: koto.AgentRequest.msg:type_name -> koto.MsgReq
	12, // 35: koto.AgentRequest.exec:type_name -> koto.ExecReq
	13, // 36: koto.AgentRequest.exec_stream:type_name -> koto.ExecStreamReq
	14, // 37: koto.AgentRequest.run_script:type_name -> koto.GuestScriptReq
	15, // 38: koto.AgentRequest.shell_attach:type_name -> koto.ShellAttachReq
	16, // 39: koto.AgentRequest.shutdown:type_name -> koto.ShutdownReq
	43, // 40: koto.AgentFrame.resize:type_name -> koto.ShellResize
	20, // 41: koto.TurnFrame.open:type_name -> koto.TurnOpen
	21, // 42: koto.TurnFrame.tool:type_name -> koto.ToolUse
	43, // [43:43] is the sub-list for method output_type
	43, // [43:43] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_guest_proto_init() }
func file_guest_proto_init() {
	if File_guest_proto != nil {
		return
	}
	file_koto_proto_init()
	file_guest_proto_msgTypes[7].OneofWrappers = []any{
		(*CtlRequest_Spawn)(nil),
		(*CtlRequest_Send)(nil),
		(*CtlRequest_Stop)(nil),
		(*CtlRequest_List)(nil),
		(*CtlRequest_Resources)(nil),
		(*CtlRequest_ConfigSet)(nil),
		(*CtlRequest_Tail)(nil),
		(*CtlRequest_JobDone)(nil),
		(*CtlRequest_Notify)(nil),
		(*CtlRequest_Report)(nil),
		(*CtlRequest_GoalDone)(nil),
		(*CtlRequest_GoalVerdict)(nil),
		(*CtlRequest_GoalSet)(nil),
		(*CtlRequest_GoalApprove)(nil),
		(*CtlRequest_GoalStatus)(nil),
		(*CtlRequest_GoalPause)(nil),
		(*CtlRequest_GoalInterrupt)(nil),
		(*CtlRequest_GoalResume)(nil),
		(*CtlRequest_GoalCancel)(nil),
		(*CtlRequest_SchedAdd)(nil),
		(*CtlRequest_SchedList)(nil),
		(*CtlRequest_SchedDel)(nil),
		(*CtlRequest_SchedToggle)(nil),
		(*CtlRequest_SchedRun)(nil),
	}
	file_guest_proto_msgTypes[9].OneofWrappers = []any{
		(*CtlResponse_Port)(nil),
		(*CtlResponse_List)(nil),
		(*CtlResponse_Resources)(nil),
		(*CtlResponse_Config)(nil),
		(*CtlResponse_Tail)(nil),
		(*CtlResponse_Goal)(nil),
		(*CtlResponse_Goals)(nil),
		(*CtlResponse_Sched)(nil),
		(*CtlResponse_Scheds)(nil),
	}
	file_guest_proto_msgTypes[17].OneofWrappers = []any{
		(*AgentRequest_Init)(nil),
		(*AgentRequest_Msg)(nil),
		(*AgentRequest_Exec)(nil),
		(*AgentRequest_ExecStream)(nil),
		(*AgentRequest_RunScript)(nil),
		(*AgentRequest_ShellAttach)(nil),
		(*AgentRequest_Shutdown)(nil),
	}
	file_guest_proto_msgTypes[19].OneofWrappers = []any{
		(*AgentFrame_Data)(nil),
		(*AgentFrame_End)(nil),
		(*AgentFrame_Error)(nil),
		(*AgentFrame_Input)(nil),
		(*AgentFrame_Resize)(nil),
	}
	file_guest_proto_msgTypes[22].OneofWrappers = []any{
		(*TurnFrame_Open)(nil),
		(*TurnFrame_Text)(nil),
		(*TurnFrame_ThinkBegin)(nil),
		(*TurnFrame_ThinkEnd)(nil),
		(*TurnFrame_Tool)(nil),
		(*TurnFrame_ToolOutBegin)(nil),
		(*TurnFrame_ToolOutEnd)(nil),
		(*TurnFrame_Err)(nil),
		(*TurnFrame_TurnEnd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guest_proto_rawDesc), len(file_guest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guest_proto_goTypes,
		DependencyIndexes: file_guest_proto_depIdxs,
		MessageInfos:      file_guest_proto_msgTypes,
	}.Build()
	File_guest_proto = out.File
	file_guest_proto_goTypes = nil
	file_guest_proto_depIdxs = nil
}
