// Wire contract shared by the koto daemon (Go), the TUI (Go), and the
// Android client (Kotlin). Generated Go code lands in ./pb (committed; run
// `make proto-gen`). Field names are snake_case to match the historical JSON
// keys the TUI still consumes via protojson(UseProtoNames:true).
//
// Conventions:
//   - proto3 scalar zero-values are not serialized, reproducing the old
//     `omitempty` behavior on the wire.
//   - protobuf has no struct embedding, so the old BaseResp{ok,error} is
//     flattened into every *Resp as fields 1 and 2.
//   - `ts` and schedule timestamps stay `double` (Python time.time() seconds);
//     History pages compare ts < before, so the float contract must hold.
//   - arbitrary JSON objects (config, metrics) map to google.protobuf.Struct.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: koto.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Koto_Spawn_FullMethodName          = "/koto.Koto/Spawn"
	Koto_Send_FullMethodName           = "/koto.Koto/Send"
	Koto_List_FullMethodName           = "/koto.Koto/List"
	Koto_Stop_FullMethodName           = "/koto.Koto/Stop"
	Koto_Interrupt_FullMethodName      = "/koto.Koto/Interrupt"
	Koto_Destroy_FullMethodName        = "/koto.Koto/Destroy"
	Koto_Restart_FullMethodName        = "/koto.Koto/Restart"
	Koto_History_FullMethodName        = "/koto.Koto/History"
	Koto_Config_FullMethodName         = "/koto.Koto/Config"
	Koto_Metrics_FullMethodName        = "/koto.Koto/Metrics"
	Koto_Clear_FullMethodName          = "/koto.Koto/Clear"
	Koto_Skills_FullMethodName         = "/koto.Koto/Skills"
	Koto_SkillNew_FullMethodName       = "/koto.Koto/SkillNew"
	Koto_SkillRead_FullMethodName      = "/koto.Koto/SkillRead"
	Koto_Jobs_FullMethodName           = "/koto.Koto/Jobs"
	Koto_JobLogs_FullMethodName        = "/koto.Koto/JobLogs"
	Koto_JobTail_FullMethodName        = "/koto.Koto/JobTail"
	Koto_SchedAdd_FullMethodName       = "/koto.Koto/SchedAdd"
	Koto_SchedList_FullMethodName      = "/koto.Koto/SchedList"
	Koto_SchedDel_FullMethodName       = "/koto.Koto/SchedDel"
	Koto_SchedToggle_FullMethodName    = "/koto.Koto/SchedToggle"
	Koto_SchedRun_FullMethodName       = "/koto.Koto/SchedRun"
	Koto_GoalSet_FullMethodName        = "/koto.Koto/GoalSet"
	Koto_GoalList_FullMethodName       = "/koto.Koto/GoalList"
	Koto_GoalApprove_FullMethodName    = "/koto.Koto/GoalApprove"
	Koto_GoalPause_FullMethodName      = "/koto.Koto/GoalPause"
	Koto_GoalInterrupt_FullMethodName  = "/koto.Koto/GoalInterrupt"
	Koto_GoalResume_FullMethodName     = "/koto.Koto/GoalResume"
	Koto_GoalCancel_FullMethodName     = "/koto.Koto/GoalCancel"
	Koto_Resources_FullMethodName      = "/koto.Koto/Resources"
	Koto_AclGet_FullMethodName         = "/koto.Koto/AclGet"
	Koto_AclSetRole_FullMethodName     = "/koto.Koto/AclSetRole"
	Koto_AclDelRole_FullMethodName     = "/koto.Koto/AclDelRole"
	Koto_RunScript_FullMethodName      = "/koto.Koto/RunScript"
	Koto_AttachShell_FullMethodName    = "/koto.Koto/AttachShell"
	Koto_SubscribeGroup_FullMethodName = "/koto.Koto/SubscribeGroup"
	Koto_SubscribeLogs_FullMethodName  = "/koto.Koto/SubscribeLogs"
	Koto_WatchState_FullMethodName     = "/koto.Koto/WatchState"
)

// KotoClient is the client API for Koto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KotoClient interface {
	// ---- unary (one per legacy dispatch case) ----
	Spawn(ctx context.Context, in *SpawnReq, opts ...grpc.CallOption) (*SpawnResp, error)
	Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*BaseResp, error)
	List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error)
	Stop(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error)
	Interrupt(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error)
	Destroy(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error)
	Restart(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*SpawnResp, error)
	History(ctx context.Context, in *HistoryReq, opts ...grpc.CallOption) (*HistoryResp, error)
	Config(ctx context.Context, in *ConfigReq, opts ...grpc.CallOption) (*ConfigResp, error)
	Metrics(ctx context.Context, in *MetricsReq, opts ...grpc.CallOption) (*MetricsResp, error)
	Clear(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error)
	Skills(ctx context.Context, in *SkillListReq, opts ...grpc.CallOption) (*SkillsResp, error)
	SkillNew(ctx context.Context, in *SkillNewReq, opts ...grpc.CallOption) (*SkillNewResp, error)
	SkillRead(ctx context.Context, in *SkillReadReq, opts ...grpc.CallOption) (*SkillReadResp, error)
	// Jobs lists a group's background jobs (cs-job) fresh from the guest —
	// group "" reads across all running groups (needs the "*" target, like
	// global metrics). JobLogs returns one job's metadata + an output tail.
	Jobs(ctx context.Context, in *JobsReq, opts ...grpc.CallOption) (*JobsResp, error)
	JobLogs(ctx context.Context, in *JobLogsReq, opts ...grpc.CallOption) (*JobLogsResp, error)
	// JobTail streams a job's combined output LIVE: an initial tail window,
	// then lines as the job writes them (guest-side `tail -c -f` over the
	// agent's exec_stream; client cancel kills the guest tail). Reuses the
	// ScriptEvent frame vocabulary (data/end/error); data chunks are whole
	// sanitized lines. Ordinary grantable verb (job_tail), group-scoped.
	JobTail(ctx context.Context, in *JobTailReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScriptEvent], error)
	SchedAdd(ctx context.Context, in *SchedAddReq, opts ...grpc.CallOption) (*SchedAddResp, error)
	SchedList(ctx context.Context, in *SchedListReq, opts ...grpc.CallOption) (*SchedListResp, error)
	SchedDel(ctx context.Context, in *SchedIDReq, opts ...grpc.CallOption) (*BaseResp, error)
	SchedToggle(ctx context.Context, in *SchedToggleReq, opts ...grpc.CallOption) (*BaseResp, error)
	SchedRun(ctx context.Context, in *SchedIDReq, opts ...grpc.CallOption) (*BaseResp, error)
	// ---- goal loop (daemon/goals.go) ----
	// A goal is "iterate this group with fresh context until an independent
	// judge accepts the acceptance criteria". At most one goal per group;
	// approve/pause/resume/cancel therefore address by group. GoalApprove is
	// the human-confirmation step for plan-first goals (status
	// awaiting_approval → running); it is an ordinary grantable verb here but
	// has deliberately NO ctl-plane counterpart — main can set a goal on a
	// peer but cannot approve one.
	// GoalInterrupt is GoalPause NOW: pause the goal (reason "interrupted")
	// and SIGINT the in-flight worker/judge turn — but only when the turn
	// currently running actually belongs to the goal loop (a goal turn queued
	// behind operator chat must not get the operator's turn killed). Resume
	// with GoalResume like any pause.
	GoalSet(ctx context.Context, in *GoalSetReq, opts ...grpc.CallOption) (*GoalResp, error)
	GoalList(ctx context.Context, in *GoalListReq, opts ...grpc.CallOption) (*GoalListResp, error)
	GoalApprove(ctx context.Context, in *GoalGroupReq, opts ...grpc.CallOption) (*GoalResp, error)
	GoalPause(ctx context.Context, in *GoalGroupReq, opts ...grpc.CallOption) (*GoalResp, error)
	GoalInterrupt(ctx context.Context, in *GoalGroupReq, opts ...grpc.CallOption) (*GoalResp, error)
	GoalResume(ctx context.Context, in *GoalGroupReq, opts ...grpc.CallOption) (*GoalResp, error)
	GoalCancel(ctx context.Context, in *GoalGroupReq, opts ...grpc.CallOption) (*GoalResp, error)
	// Resources reports host-side resource consumption for the whole fleet:
	// per-group workspace.img allocation + growth rate + FC process CPU/RSS,
	// plus a host rollup (filesystem free vs. what the images occupy vs. what
	// the `size` presets have provisioned).
	//
	// GLOBAL and UNTARGETED by design — it is a cluster-wide rollup with no
	// group field, so it is granted by verb alone and reads across every group
	// (see targetOf in daemon/acl.go). The admin role has it via the hardcoded
	// superuser rule; it is NOT in adminOnlyVerbs, so a read-only monitoring
	// role can be granted `resources` through acl.json.
	//
	// Every figure is collected host-side (stat/statfs//proc) and never from a
	// guest exec, so it stays truthful when a guest is wedged, read-only, or
	// stopped — the failure mode where a guest's own `df` is actively
	// misleading. See daemon/resources.go.
	Resources(ctx context.Context, in *ResourcesReq, opts ...grpc.CallOption) (*ResourcesResp, error)
	// ---- ACL management (HARDCODED admin-only: these verbs can never be
	// granted via acl.json — a role granting itself acl_set_role would be
	// privilege escalation to full control; see daemon/acl.go) ----
	AclGet(ctx context.Context, in *AclGetReq, opts ...grpc.CallOption) (*AclResp, error)
	AclSetRole(ctx context.Context, in *AclSetRoleReq, opts ...grpc.CallOption) (*AclResp, error)
	AclDelRole(ctx context.Context, in *AclDelRoleReq, opts ...grpc.CallOption) (*AclResp, error)
	// RunScript executes a POSIX sh script inside a group's microVM as the
	// guest worker user (node, uid 1000, cwd /workspace) and streams its
	// combined stdout+stderr live. Also HARDCODED admin-only (daemon/acl.go):
	// it is direct code execution in the VM, bypassing the agent loop, so it
	// is not delegatable via acl.json. Client cancel kills the script's
	// process group in the guest. Frames: `data` (chunk bytes) … `end`;
	// failures surface as one `error` frame (in-band, like {ok,error}).
	// No exit code is carried — append `; echo rc=$?` if you need it.
	RunScript(ctx context.Context, in *RunScriptReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScriptEvent], error)
	// AttachShell is the first bidi-streaming RPC in this file: the client
	// sends a stream of ShellInput (one `open`, then any number of `data` /
	// `resize` messages as the human types/resizes their terminal) and
	// receives a stream of ShellFrame (raw PTY output). It attaches to a
	// persistent tmux session in the group's guest VM (default "koto-shell") —
	// tmux itself, not this RPC, owns multi-attach mirroring and survival
	// across client disconnects (see daemon/fc.go fcShellDial, fcguest/main.go
	// handleShellAttach). An ordinary per-role grantable verb (attach_shell),
	// NOT hardcoded admin-only like run_script — see daemon/acl.go: unlike
	// run_script this is meant to be agent-cooperative, not an operator bypass.
	//
	// `group` is repeated on every ShellInput variant, not just `open`. This
	// isn't redundancy for its own sake: daemon/auth.go's aclStream.RecvMsg
	// re-authorizes EVERY client-sent message against its own decoded target,
	// so a `data`/`resize` message without `group` would silently downgrade to
	// verb-only authorization instead of verb+target for the rest of the
	// stream. The daemon captures `group` from the `open` message and treats
	// it as fixed for the life of the call — a later message naming a
	// different (even if independently-authorized) group is a protocol error.
	AttachShell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellInput, ShellFrame], error)
	// ---- server-streaming (the old connection-ownership-transfer cases) ----
	// Stream-open replaces the old {ok,subscribed} ack frame. A bad group or
	// failed auth surfaces as a non-OK gRPC status at open time.
	SubscribeGroup(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	SubscribeLogs(ctx context.Context, in *LogsReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEvent], error)
	// WatchState pushes a full group-state snapshot whenever it changes
	// (spawn/stop/stall/queue-depth/config), replacing client-side List
	// polling. The first frame arrives immediately; later frames only on
	// change. Snapshots are idempotent — a client may miss intermediate
	// frames and still converge on the latest one.
	WatchState(ctx context.Context, in *WatchReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateFrame], error)
}

type kotoClient struct {
	cc grpc.ClientConnInterface
}

func NewKotoClient(cc grpc.ClientConnInterface) KotoClient {
	return &kotoClient{cc}
}

func (c *kotoClient) Spawn(ctx context.Context, in *SpawnReq, opts ...grpc.CallOption) (*SpawnResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnResp)
	err := c.cc.Invoke(ctx, Koto_Spawn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Koto_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResp)
	err := c.cc.Invoke(ctx, Koto_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) Stop(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Koto_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) Interrupt(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Koto_Interrupt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) Destroy(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Koto_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) Restart(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*SpawnResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnResp)
	err := c.cc.Invoke(ctx, Koto_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) History(ctx context.Context, in *HistoryReq, opts ...grpc.CallOption) (*HistoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResp)
	err := c.cc.Invoke(ctx, Koto_History_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) Config(ctx context.Context, in *ConfigReq, opts ...grpc.CallOption) (*ConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResp)
	err := c.cc.Invoke(ctx, Koto_Config_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) Metrics(ctx context.Context, in *MetricsReq, opts ...grpc.CallOption) (*MetricsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResp)
	err := c.cc.Invoke(ctx, Koto_Metrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) Clear(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Koto_Clear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) Skills(ctx context.Context, in *SkillListReq, opts ...grpc.CallOption) (*SkillsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillsResp)
	err := c.cc.Invoke(ctx, Koto_Skills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) SkillNew(ctx context.Context, in *SkillNewReq, opts ...grpc.CallOption) (*SkillNewResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillNewResp)
	err := c.cc.Invoke(ctx, Koto_SkillNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) SkillRead(ctx context.Context, in *SkillReadReq, opts ...grpc.CallOption) (*SkillReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillReadResp)
	err := c.cc.Invoke(ctx, Koto_SkillRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) Jobs(ctx context.Context, in *JobsReq, opts ...grpc.CallOption) (*JobsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobsResp)
	err := c.cc.Invoke(ctx, Koto_Jobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) JobLogs(ctx context.Context, in *JobLogsReq, opts ...grpc.CallOption) (*JobLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobLogsResp)
	err := c.cc.Invoke(ctx, Koto_JobLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) JobTail(ctx context.Context, in *JobTailReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScriptEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Koto_ServiceDesc.Streams[0], Koto_JobTail_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JobTailReq, ScriptEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Koto_JobTailClient = grpc.ServerStreamingClient[ScriptEvent]

func (c *kotoClient) SchedAdd(ctx context.Context, in *SchedAddReq, opts ...grpc.CallOption) (*SchedAddResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedAddResp)
	err := c.cc.Invoke(ctx, Koto_SchedAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) SchedList(ctx context.Context, in *SchedListReq, opts ...grpc.CallOption) (*SchedListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedListResp)
	err := c.cc.Invoke(ctx, Koto_SchedList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) SchedDel(ctx context.Context, in *SchedIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Koto_SchedDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) SchedToggle(ctx context.Context, in *SchedToggleReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Koto_SchedToggle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) SchedRun(ctx context.Context, in *SchedIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Koto_SchedRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) GoalSet(ctx context.Context, in *GoalSetReq, opts ...grpc.CallOption) (*GoalResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoalResp)
	err := c.cc.Invoke(ctx, Koto_GoalSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) GoalList(ctx context.Context, in *GoalListReq, opts ...grpc.CallOption) (*GoalListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoalListResp)
	err := c.cc.Invoke(ctx, Koto_GoalList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) GoalApprove(ctx context.Context, in *GoalGroupReq, opts ...grpc.CallOption) (*GoalResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoalResp)
	err := c.cc.Invoke(ctx, Koto_GoalApprove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) GoalPause(ctx context.Context, in *GoalGroupReq, opts ...grpc.CallOption) (*GoalResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoalResp)
	err := c.cc.Invoke(ctx, Koto_GoalPause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) GoalInterrupt(ctx context.Context, in *GoalGroupReq, opts ...grpc.CallOption) (*GoalResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoalResp)
	err := c.cc.Invoke(ctx, Koto_GoalInterrupt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) GoalResume(ctx context.Context, in *GoalGroupReq, opts ...grpc.CallOption) (*GoalResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoalResp)
	err := c.cc.Invoke(ctx, Koto_GoalResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) GoalCancel(ctx context.Context, in *GoalGroupReq, opts ...grpc.CallOption) (*GoalResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoalResp)
	err := c.cc.Invoke(ctx, Koto_GoalCancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) Resources(ctx context.Context, in *ResourcesReq, opts ...grpc.CallOption) (*ResourcesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcesResp)
	err := c.cc.Invoke(ctx, Koto_Resources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) AclGet(ctx context.Context, in *AclGetReq, opts ...grpc.CallOption) (*AclResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AclResp)
	err := c.cc.Invoke(ctx, Koto_AclGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) AclSetRole(ctx context.Context, in *AclSetRoleReq, opts ...grpc.CallOption) (*AclResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AclResp)
	err := c.cc.Invoke(ctx, Koto_AclSetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) AclDelRole(ctx context.Context, in *AclDelRoleReq, opts ...grpc.CallOption) (*AclResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AclResp)
	err := c.cc.Invoke(ctx, Koto_AclDelRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotoClient) RunScript(ctx context.Context, in *RunScriptReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScriptEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Koto_ServiceDesc.Streams[1], Koto_RunScript_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunScriptReq, ScriptEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Koto_RunScriptClient = grpc.ServerStreamingClient[ScriptEvent]

func (c *kotoClient) AttachShell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellInput, ShellFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Koto_ServiceDesc.Streams[2], Koto_AttachShell_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShellInput, ShellFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Koto_AttachShellClient = grpc.BidiStreamingClient[ShellInput, ShellFrame]

func (c *kotoClient) SubscribeGroup(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Koto_ServiceDesc.Streams[3], Koto_SubscribeGroup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeReq, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Koto_SubscribeGroupClient = grpc.ServerStreamingClient[Event]

func (c *kotoClient) SubscribeLogs(ctx context.Context, in *LogsReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Koto_ServiceDesc.Streams[4], Koto_SubscribeLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsReq, LogEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Koto_SubscribeLogsClient = grpc.ServerStreamingClient[LogEvent]

func (c *kotoClient) WatchState(ctx context.Context, in *WatchReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Koto_ServiceDesc.Streams[5], Koto_WatchState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchReq, StateFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Koto_WatchStateClient = grpc.ServerStreamingClient[StateFrame]

// KotoServer is the server API for Koto service.
// All implementations must embed UnimplementedKotoServer
// for forward compatibility.
type KotoServer interface {
	// ---- unary (one per legacy dispatch case) ----
	Spawn(context.Context, *SpawnReq) (*SpawnResp, error)
	Send(context.Context, *SendReq) (*BaseResp, error)
	List(context.Context, *ListReq) (*ListResp, error)
	Stop(context.Context, *GroupReq) (*BaseResp, error)
	Interrupt(context.Context, *GroupReq) (*BaseResp, error)
	Destroy(context.Context, *GroupReq) (*BaseResp, error)
	Restart(context.Context, *GroupReq) (*SpawnResp, error)
	History(context.Context, *HistoryReq) (*HistoryResp, error)
	Config(context.Context, *ConfigReq) (*ConfigResp, error)
	Metrics(context.Context, *MetricsReq) (*MetricsResp, error)
	Clear(context.Context, *GroupReq) (*BaseResp, error)
	Skills(context.Context, *SkillListReq) (*SkillsResp, error)
	SkillNew(context.Context, *SkillNewReq) (*SkillNewResp, error)
	SkillRead(context.Context, *SkillReadReq) (*SkillReadResp, error)
	// Jobs lists a group's background jobs (cs-job) fresh from the guest —
	// group "" reads across all running groups (needs the "*" target, like
	// global metrics). JobLogs returns one job's metadata + an output tail.
	Jobs(context.Context, *JobsReq) (*JobsResp, error)
	JobLogs(context.Context, *JobLogsReq) (*JobLogsResp, error)
	// JobTail streams a job's combined output LIVE: an initial tail window,
	// then lines as the job writes them (guest-side `tail -c -f` over the
	// agent's exec_stream; client cancel kills the guest tail). Reuses the
	// ScriptEvent frame vocabulary (data/end/error); data chunks are whole
	// sanitized lines. Ordinary grantable verb (job_tail), group-scoped.
	JobTail(*JobTailReq, grpc.ServerStreamingServer[ScriptEvent]) error
	SchedAdd(context.Context, *SchedAddReq) (*SchedAddResp, error)
	SchedList(context.Context, *SchedListReq) (*SchedListResp, error)
	SchedDel(context.Context, *SchedIDReq) (*BaseResp, error)
	SchedToggle(context.Context, *SchedToggleReq) (*BaseResp, error)
	SchedRun(context.Context, *SchedIDReq) (*BaseResp, error)
	// ---- goal loop (daemon/goals.go) ----
	// A goal is "iterate this group with fresh context until an independent
	// judge accepts the acceptance criteria". At most one goal per group;
	// approve/pause/resume/cancel therefore address by group. GoalApprove is
	// the human-confirmation step for plan-first goals (status
	// awaiting_approval → running); it is an ordinary grantable verb here but
	// has deliberately NO ctl-plane counterpart — main can set a goal on a
	// peer but cannot approve one.
	// GoalInterrupt is GoalPause NOW: pause the goal (reason "interrupted")
	// and SIGINT the in-flight worker/judge turn — but only when the turn
	// currently running actually belongs to the goal loop (a goal turn queued
	// behind operator chat must not get the operator's turn killed). Resume
	// with GoalResume like any pause.
	GoalSet(context.Context, *GoalSetReq) (*GoalResp, error)
	GoalList(context.Context, *GoalListReq) (*GoalListResp, error)
	GoalApprove(context.Context, *GoalGroupReq) (*GoalResp, error)
	GoalPause(context.Context, *GoalGroupReq) (*GoalResp, error)
	GoalInterrupt(context.Context, *GoalGroupReq) (*GoalResp, error)
	GoalResume(context.Context, *GoalGroupReq) (*GoalResp, error)
	GoalCancel(context.Context, *GoalGroupReq) (*GoalResp, error)
	// Resources reports host-side resource consumption for the whole fleet:
	// per-group workspace.img allocation + growth rate + FC process CPU/RSS,
	// plus a host rollup (filesystem free vs. what the images occupy vs. what
	// the `size` presets have provisioned).
	//
	// GLOBAL and UNTARGETED by design — it is a cluster-wide rollup with no
	// group field, so it is granted by verb alone and reads across every group
	// (see targetOf in daemon/acl.go). The admin role has it via the hardcoded
	// superuser rule; it is NOT in adminOnlyVerbs, so a read-only monitoring
	// role can be granted `resources` through acl.json.
	//
	// Every figure is collected host-side (stat/statfs//proc) and never from a
	// guest exec, so it stays truthful when a guest is wedged, read-only, or
	// stopped — the failure mode where a guest's own `df` is actively
	// misleading. See daemon/resources.go.
	Resources(context.Context, *ResourcesReq) (*ResourcesResp, error)
	// ---- ACL management (HARDCODED admin-only: these verbs can never be
	// granted via acl.json — a role granting itself acl_set_role would be
	// privilege escalation to full control; see daemon/acl.go) ----
	AclGet(context.Context, *AclGetReq) (*AclResp, error)
	AclSetRole(context.Context, *AclSetRoleReq) (*AclResp, error)
	AclDelRole(context.Context, *AclDelRoleReq) (*AclResp, error)
	// RunScript executes a POSIX sh script inside a group's microVM as the
	// guest worker user (node, uid 1000, cwd /workspace) and streams its
	// combined stdout+stderr live. Also HARDCODED admin-only (daemon/acl.go):
	// it is direct code execution in the VM, bypassing the agent loop, so it
	// is not delegatable via acl.json. Client cancel kills the script's
	// process group in the guest. Frames: `data` (chunk bytes) … `end`;
	// failures surface as one `error` frame (in-band, like {ok,error}).
	// No exit code is carried — append `; echo rc=$?` if you need it.
	RunScript(*RunScriptReq, grpc.ServerStreamingServer[ScriptEvent]) error
	// AttachShell is the first bidi-streaming RPC in this file: the client
	// sends a stream of ShellInput (one `open`, then any number of `data` /
	// `resize` messages as the human types/resizes their terminal) and
	// receives a stream of ShellFrame (raw PTY output). It attaches to a
	// persistent tmux session in the group's guest VM (default "koto-shell") —
	// tmux itself, not this RPC, owns multi-attach mirroring and survival
	// across client disconnects (see daemon/fc.go fcShellDial, fcguest/main.go
	// handleShellAttach). An ordinary per-role grantable verb (attach_shell),
	// NOT hardcoded admin-only like run_script — see daemon/acl.go: unlike
	// run_script this is meant to be agent-cooperative, not an operator bypass.
	//
	// `group` is repeated on every ShellInput variant, not just `open`. This
	// isn't redundancy for its own sake: daemon/auth.go's aclStream.RecvMsg
	// re-authorizes EVERY client-sent message against its own decoded target,
	// so a `data`/`resize` message without `group` would silently downgrade to
	// verb-only authorization instead of verb+target for the rest of the
	// stream. The daemon captures `group` from the `open` message and treats
	// it as fixed for the life of the call — a later message naming a
	// different (even if independently-authorized) group is a protocol error.
	AttachShell(grpc.BidiStreamingServer[ShellInput, ShellFrame]) error
	// ---- server-streaming (the old connection-ownership-transfer cases) ----
	// Stream-open replaces the old {ok,subscribed} ack frame. A bad group or
	// failed auth surfaces as a non-OK gRPC status at open time.
	SubscribeGroup(*SubscribeReq, grpc.ServerStreamingServer[Event]) error
	SubscribeLogs(*LogsReq, grpc.ServerStreamingServer[LogEvent]) error
	// WatchState pushes a full group-state snapshot whenever it changes
	// (spawn/stop/stall/queue-depth/config), replacing client-side List
	// polling. The first frame arrives immediately; later frames only on
	// change. Snapshots are idempotent — a client may miss intermediate
	// frames and still converge on the latest one.
	WatchState(*WatchReq, grpc.ServerStreamingServer[StateFrame]) error
	mustEmbedUnimplementedKotoServer()
}

// UnimplementedKotoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKotoServer struct{}

func (UnimplementedKotoServer) Spawn(context.Context, *SpawnReq) (*SpawnResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Spawn not implemented")
}
func (UnimplementedKotoServer) Send(context.Context, *SendReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedKotoServer) List(context.Context, *ListReq) (*ListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedKotoServer) Stop(context.Context, *GroupReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedKotoServer) Interrupt(context.Context, *GroupReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Interrupt not implemented")
}
func (UnimplementedKotoServer) Destroy(context.Context, *GroupReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedKotoServer) Restart(context.Context, *GroupReq) (*SpawnResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedKotoServer) History(context.Context, *HistoryReq) (*HistoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method History not implemented")
}
func (UnimplementedKotoServer) Config(context.Context, *ConfigReq) (*ConfigResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Config not implemented")
}
func (UnimplementedKotoServer) Metrics(context.Context, *MetricsReq) (*MetricsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Metrics not implemented")
}
func (UnimplementedKotoServer) Clear(context.Context, *GroupReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Clear not implemented")
}
func (UnimplementedKotoServer) Skills(context.Context, *SkillListReq) (*SkillsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Skills not implemented")
}
func (UnimplementedKotoServer) SkillNew(context.Context, *SkillNewReq) (*SkillNewResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SkillNew not implemented")
}
func (UnimplementedKotoServer) SkillRead(context.Context, *SkillReadReq) (*SkillReadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SkillRead not implemented")
}
func (UnimplementedKotoServer) Jobs(context.Context, *JobsReq) (*JobsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Jobs not implemented")
}
func (UnimplementedKotoServer) JobLogs(context.Context, *JobLogsReq) (*JobLogsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method JobLogs not implemented")
}
func (UnimplementedKotoServer) JobTail(*JobTailReq, grpc.ServerStreamingServer[ScriptEvent]) error {
	return status.Error(codes.Unimplemented, "method JobTail not implemented")
}
func (UnimplementedKotoServer) SchedAdd(context.Context, *SchedAddReq) (*SchedAddResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedAdd not implemented")
}
func (UnimplementedKotoServer) SchedList(context.Context, *SchedListReq) (*SchedListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedList not implemented")
}
func (UnimplementedKotoServer) SchedDel(context.Context, *SchedIDReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedDel not implemented")
}
func (UnimplementedKotoServer) SchedToggle(context.Context, *SchedToggleReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedToggle not implemented")
}
func (UnimplementedKotoServer) SchedRun(context.Context, *SchedIDReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedRun not implemented")
}
func (UnimplementedKotoServer) GoalSet(context.Context, *GoalSetReq) (*GoalResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GoalSet not implemented")
}
func (UnimplementedKotoServer) GoalList(context.Context, *GoalListReq) (*GoalListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GoalList not implemented")
}
func (UnimplementedKotoServer) GoalApprove(context.Context, *GoalGroupReq) (*GoalResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GoalApprove not implemented")
}
func (UnimplementedKotoServer) GoalPause(context.Context, *GoalGroupReq) (*GoalResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GoalPause not implemented")
}
func (UnimplementedKotoServer) GoalInterrupt(context.Context, *GoalGroupReq) (*GoalResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GoalInterrupt not implemented")
}
func (UnimplementedKotoServer) GoalResume(context.Context, *GoalGroupReq) (*GoalResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GoalResume not implemented")
}
func (UnimplementedKotoServer) GoalCancel(context.Context, *GoalGroupReq) (*GoalResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GoalCancel not implemented")
}
func (UnimplementedKotoServer) Resources(context.Context, *ResourcesReq) (*ResourcesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Resources not implemented")
}
func (UnimplementedKotoServer) AclGet(context.Context, *AclGetReq) (*AclResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AclGet not implemented")
}
func (UnimplementedKotoServer) AclSetRole(context.Context, *AclSetRoleReq) (*AclResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AclSetRole not implemented")
}
func (UnimplementedKotoServer) AclDelRole(context.Context, *AclDelRoleReq) (*AclResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AclDelRole not implemented")
}
func (UnimplementedKotoServer) RunScript(*RunScriptReq, grpc.ServerStreamingServer[ScriptEvent]) error {
	return status.Error(codes.Unimplemented, "method RunScript not implemented")
}
func (UnimplementedKotoServer) AttachShell(grpc.BidiStreamingServer[ShellInput, ShellFrame]) error {
	return status.Error(codes.Unimplemented, "method AttachShell not implemented")
}
func (UnimplementedKotoServer) SubscribeGroup(*SubscribeReq, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method SubscribeGroup not implemented")
}
func (UnimplementedKotoServer) SubscribeLogs(*LogsReq, grpc.ServerStreamingServer[LogEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeLogs not implemented")
}
func (UnimplementedKotoServer) WatchState(*WatchReq, grpc.ServerStreamingServer[StateFrame]) error {
	return status.Error(codes.Unimplemented, "method WatchState not implemented")
}
func (UnimplementedKotoServer) mustEmbedUnimplementedKotoServer() {}
func (UnimplementedKotoServer) testEmbeddedByValue()              {}

// UnsafeKotoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KotoServer will
// result in compilation errors.
type UnsafeKotoServer interface {
	mustEmbedUnimplementedKotoServer()
}

func RegisterKotoServer(s grpc.ServiceRegistrar, srv KotoServer) {
	// If the following call panics, it indicates UnimplementedKotoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Koto_ServiceDesc, srv)
}

func _Koto_Spawn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).Spawn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_Spawn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).Spawn(ctx, req.(*SpawnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).Send(ctx, req.(*SendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).List(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).Stop(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_Interrupt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).Interrupt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_Interrupt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).Interrupt(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).Destroy(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).Restart(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_History_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).History(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_History_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).History(ctx, req.(*HistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_Config_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).Config(ctx, req.(*ConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_Metrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).Metrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_Metrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).Metrics(ctx, req.(*MetricsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_Clear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).Clear(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_Skills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).Skills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_Skills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).Skills(ctx, req.(*SkillListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_SkillNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillNewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).SkillNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_SkillNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).SkillNew(ctx, req.(*SkillNewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_SkillRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).SkillRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_SkillRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).SkillRead(ctx, req.(*SkillReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_Jobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).Jobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_Jobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).Jobs(ctx, req.(*JobsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_JobLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).JobLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_JobLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).JobLogs(ctx, req.(*JobLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_JobTail_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobTailReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KotoServer).JobTail(m, &grpc.GenericServerStream[JobTailReq, ScriptEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Koto_JobTailServer = grpc.ServerStreamingServer[ScriptEvent]

func _Koto_SchedAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).SchedAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_SchedAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).SchedAdd(ctx, req.(*SchedAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_SchedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).SchedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_SchedList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).SchedList(ctx, req.(*SchedListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_SchedDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).SchedDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_SchedDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).SchedDel(ctx, req.(*SchedIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_SchedToggle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedToggleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).SchedToggle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_SchedToggle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).SchedToggle(ctx, req.(*SchedToggleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_SchedRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).SchedRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_SchedRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).SchedRun(ctx, req.(*SchedIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_GoalSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoalSetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).GoalSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_GoalSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).GoalSet(ctx, req.(*GoalSetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_GoalList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoalListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).GoalList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_GoalList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).GoalList(ctx, req.(*GoalListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_GoalApprove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoalGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).GoalApprove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_GoalApprove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).GoalApprove(ctx, req.(*GoalGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_GoalPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoalGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).GoalPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_GoalPause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).GoalPause(ctx, req.(*GoalGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_GoalInterrupt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoalGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).GoalInterrupt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_GoalInterrupt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).GoalInterrupt(ctx, req.(*GoalGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_GoalResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoalGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).GoalResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_GoalResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).GoalResume(ctx, req.(*GoalGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_GoalCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoalGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).GoalCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_GoalCancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).GoalCancel(ctx, req.(*GoalGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_Resources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourcesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).Resources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_Resources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).Resources(ctx, req.(*ResourcesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_AclGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AclGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).AclGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_AclGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).AclGet(ctx, req.(*AclGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_AclSetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AclSetRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).AclSetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_AclSetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).AclSetRole(ctx, req.(*AclSetRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_AclDelRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AclDelRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotoServer).AclDelRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Koto_AclDelRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotoServer).AclDelRole(ctx, req.(*AclDelRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koto_RunScript_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunScriptReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KotoServer).RunScript(m, &grpc.GenericServerStream[RunScriptReq, ScriptEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Koto_RunScriptServer = grpc.ServerStreamingServer[ScriptEvent]

func _Koto_AttachShell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KotoServer).AttachShell(&grpc.GenericServerStream[ShellInput, ShellFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Koto_AttachShellServer = grpc.BidiStreamingServer[ShellInput, ShellFrame]

func _Koto_SubscribeGroup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KotoServer).SubscribeGroup(m, &grpc.GenericServerStream[SubscribeReq, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Koto_SubscribeGroupServer = grpc.ServerStreamingServer[Event]

func _Koto_SubscribeLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KotoServer).SubscribeLogs(m, &grpc.GenericServerStream[LogsReq, LogEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Koto_SubscribeLogsServer = grpc.ServerStreamingServer[LogEvent]

func _Koto_WatchState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KotoServer).WatchState(m, &grpc.GenericServerStream[WatchReq, StateFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Koto_WatchStateServer = grpc.ServerStreamingServer[StateFrame]

// Koto_ServiceDesc is the grpc.ServiceDesc for Koto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Koto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "koto.Koto",
	HandlerType: (*KotoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Spawn",
			Handler:    _Koto_Spawn_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Koto_Send_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Koto_List_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Koto_Stop_Handler,
		},
		{
			MethodName: "Interrupt",
			Handler:    _Koto_Interrupt_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _Koto_Destroy_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _Koto_Restart_Handler,
		},
		{
			MethodName: "History",
			Handler:    _Koto_History_Handler,
		},
		{
			MethodName: "Config",
			Handler:    _Koto_Config_Handler,
		},
		{
			MethodName: "Metrics",
			Handler:    _Koto_Metrics_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _Koto_Clear_Handler,
		},
		{
			MethodName: "Skills",
			Handler:    _Koto_Skills_Handler,
		},
		{
			MethodName: "SkillNew",
			Handler:    _Koto_SkillNew_Handler,
		},
		{
			MethodName: "SkillRead",
			Handler:    _Koto_SkillRead_Handler,
		},
		{
			MethodName: "Jobs",
			Handler:    _Koto_Jobs_Handler,
		},
		{
			MethodName: "JobLogs",
			Handler:    _Koto_JobLogs_Handler,
		},
		{
			MethodName: "SchedAdd",
			Handler:    _Koto_SchedAdd_Handler,
		},
		{
			MethodName: "SchedList",
			Handler:    _Koto_SchedList_Handler,
		},
		{
			MethodName: "SchedDel",
			Handler:    _Koto_SchedDel_Handler,
		},
		{
			MethodName: "SchedToggle",
			Handler:    _Koto_SchedToggle_Handler,
		},
		{
			MethodName: "SchedRun",
			Handler:    _Koto_SchedRun_Handler,
		},
		{
			MethodName: "GoalSet",
			Handler:    _Koto_GoalSet_Handler,
		},
		{
			MethodName: "GoalList",
			Handler:    _Koto_GoalList_Handler,
		},
		{
			MethodName: "GoalApprove",
			Handler:    _Koto_GoalApprove_Handler,
		},
		{
			MethodName: "GoalPause",
			Handler:    _Koto_GoalPause_Handler,
		},
		{
			MethodName: "GoalInterrupt",
			Handler:    _Koto_GoalInterrupt_Handler,
		},
		{
			MethodName: "GoalResume",
			Handler:    _Koto_GoalResume_Handler,
		},
		{
			MethodName: "GoalCancel",
			Handler:    _Koto_GoalCancel_Handler,
		},
		{
			MethodName: "Resources",
			Handler:    _Koto_Resources_Handler,
		},
		{
			MethodName: "AclGet",
			Handler:    _Koto_AclGet_Handler,
		},
		{
			MethodName: "AclSetRole",
			Handler:    _Koto_AclSetRole_Handler,
		},
		{
			MethodName: "AclDelRole",
			Handler:    _Koto_AclDelRole_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JobTail",
			Handler:       _Koto_JobTail_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RunScript",
			Handler:       _Koto_RunScript_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AttachShell",
			Handler:       _Koto_AttachShell_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeGroup",
			Handler:       _Koto_SubscribeGroup_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeLogs",
			Handler:       _Koto_SubscribeLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchState",
			Handler:       _Koto_WatchState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "koto.proto",
}
