package main

import (
	"context"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/peer"
	"google.golang.org/grpc/status"
)

// Auth has three on-the-wire layers (a WireGuard overlay sits below them, out
// of process): TLS server cert, mTLS client cert (verified against the private
// CA plus a fingerprint allowlist for revocation), and a bearer token checked
// per call. All material lives in creds/ (gitignored), generated by
// `make pki-init` / `make pki-client`.

func credFile(name string) string { return filepath.Join(HERE, "creds", name) }

// serverTLSConfig builds the mTLS server config: present server.crt, require &
// verify a client cert chaining to ca.crt, then additionally require the client
// cert's SHA-256 fingerprint to be in creds/clients.allow. The allowlist is
// read on every handshake so revoking a device (delete its line) takes effect
// without a daemon restart.
func serverTLSConfig() (*tls.Config, error) {
	cert, err := tls.LoadX509KeyPair(credFile("server.crt"), credFile("server.key"))
	if err != nil {
		return nil, fmt.Errorf("server cert: %w", err)
	}
	caPEM, err := os.ReadFile(credFile("ca.crt"))
	if err != nil {
		return nil, fmt.Errorf("ca: %w", err)
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		return nil, errors.New("ca.crt: no certificates parsed")
	}
	return &tls.Config{
		Certificates: []tls.Certificate{cert},
		ClientAuth:   tls.RequireAndVerifyClientCert,
		ClientCAs:    pool,
		MinVersion:   tls.VersionTLS13,
		VerifyPeerCertificate: func(rawCerts [][]byte, _ [][]*x509.Certificate) error {
			if len(rawCerts) == 0 {
				return errors.New("no client certificate")
			}
			fp := sha256.Sum256(rawCerts[0]) // leaf is rawCerts[0]
			hexFP := hex.EncodeToString(fp[:])
			allow, err := loadClientAllow()
			if err != nil {
				return fmt.Errorf("clients.allow: %w", err)
			}
			if !allow[hexFP] {
				return fmt.Errorf("client cert %s not in allowlist", hexFP)
			}
			return nil
		},
	}, nil
}

// loadClientAllow parses creds/clients.allow ("<sha256hex> <name>" per line)
// into a set of lowercased fingerprints.
func loadClientAllow() (map[string]bool, error) {
	b, err := os.ReadFile(credFile("clients.allow"))
	if err != nil {
		return nil, err
	}
	out := map[string]bool{}
	for _, line := range strings.Split(string(b), "\n") {
		fields := strings.Fields(line)
		if len(fields) >= 1 && fields[0] != "" && !strings.HasPrefix(fields[0], "#") {
			out[strings.ToLower(fields[0])] = true
		}
	}
	return out, nil
}

// loadTokens reads creds/tokens.json ({"<name>": "<sha256hex-of-token>"}) into a
// set of valid token hashes. Read per call so rotation needs no restart.
func loadTokens() map[string]bool {
	b, err := os.ReadFile(credFile("tokens.json"))
	if err != nil {
		return nil
	}
	var m map[string]string
	if json.Unmarshal(b, &m) != nil {
		return nil
	}
	out := make(map[string]bool, len(m))
	for _, h := range m {
		out[strings.ToLower(strings.TrimSpace(h))] = true
	}
	return out
}

// tokenValid hashes the presented bearer token and checks set membership. Both
// sides are SHA-256 hashes, so a plain lookup leaks no usable timing (preimage
// resistance) — the secret never sits in memory as plaintext for comparison.
func tokenValid(tok string) bool {
	if tok == "" {
		return false
	}
	sum := sha256.Sum256([]byte(tok))
	return loadTokens()[hex.EncodeToString(sum[:])]
}

func peerAddr(ctx context.Context) string {
	if p, ok := peer.FromContext(ctx); ok && p.Addr != nil {
		return p.Addr.String()
	}
	return "?"
}

// authFromCtx enforces the bearer token. mTLS (cert chain + fingerprint
// allowlist) is already enforced by the TLS layer before any RPC dispatches, so
// reaching here means the peer holds a valid allowlisted client cert.
func authFromCtx(ctx context.Context) error {
	md, _ := metadata.FromIncomingContext(ctx)
	tok := ""
	if vals := md.Get("authorization"); len(vals) > 0 {
		tok = strings.TrimSpace(strings.TrimPrefix(vals[0], "Bearer "))
	}
	if !tokenValid(tok) {
		emitLogf("warn", "auth: rejected call from %s (bad/missing token)", peerAddr(ctx))
		return status.Error(codes.Unauthenticated, "invalid or missing token")
	}
	return nil
}

func authUnary(ctx context.Context, req any, _ *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (any, error) {
	if err := authFromCtx(ctx); err != nil {
		return nil, err
	}
	return handler(ctx, req)
}

func authStream(srv any, ss grpc.ServerStream, _ *grpc.StreamServerInfo, handler grpc.StreamHandler) error {
	if err := authFromCtx(ss.Context()); err != nil {
		return err
	}
	return handler(srv, ss)
}
