package main

import (
	"context"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/peer"
	"google.golang.org/grpc/status"
)

// Auth has three on-the-wire layers (a WireGuard overlay sits below them, out
// of process): TLS server cert, mTLS client cert (verified against the private
// CA plus a fingerprint allowlist for revocation), and a bearer token checked
// per call. All material lives in creds/ (gitignored), generated by
// `make pki-init` / `make pki-client`.

func credFile(name string) string { return filepath.Join(HERE, "creds", name) }

// serverTLSConfig builds the mTLS server config: present server.crt, require &
// verify a client cert chaining to ca.crt, then additionally require the client
// cert's SHA-256 fingerprint to be in creds/clients.allow. The allowlist is
// read on every handshake so revoking a device (delete its line) takes effect
// without a daemon restart.
func serverTLSConfig() (*tls.Config, error) {
	cert, err := tls.LoadX509KeyPair(credFile("server.crt"), credFile("server.key"))
	if err != nil {
		return nil, fmt.Errorf("server cert: %w", err)
	}
	caPEM, err := os.ReadFile(credFile("ca.crt"))
	if err != nil {
		return nil, fmt.Errorf("ca: %w", err)
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		return nil, errors.New("ca.crt: no certificates parsed")
	}
	return &tls.Config{
		Certificates: []tls.Certificate{cert},
		ClientAuth:   tls.RequireAndVerifyClientCert,
		ClientCAs:    pool,
		MinVersion:   tls.VersionTLS13,
		VerifyPeerCertificate: func(rawCerts [][]byte, _ [][]*x509.Certificate) error {
			if len(rawCerts) == 0 {
				return errors.New("no client certificate")
			}
			fp := sha256.Sum256(rawCerts[0]) // leaf is rawCerts[0]
			hexFP := hex.EncodeToString(fp[:])
			allow, err := loadClientAllow()
			if err != nil {
				return fmt.Errorf("clients.allow: %w", err)
			}
			if !allow[hexFP] {
				return fmt.Errorf("client cert %s not in allowlist", hexFP)
			}
			return nil
		},
	}, nil
}

// loadClientAllow parses creds/clients.allow ("<sha256hex> <name>" per line)
// into a set of lowercased fingerprints.
func loadClientAllow() (map[string]bool, error) {
	b, err := os.ReadFile(credFile("clients.allow"))
	if err != nil {
		return nil, err
	}
	out := map[string]bool{}
	for _, line := range strings.Split(string(b), "\n") {
		fields := strings.Fields(line)
		if len(fields) >= 1 && fields[0] != "" && !strings.HasPrefix(fields[0], "#") {
			out[strings.ToLower(fields[0])] = true
		}
	}
	return out, nil
}

// tokenIdentity hashes the presented bearer token and looks up the matching
// tokens.json entry (see acl.go for the file shape). Both sides are SHA-256
// hashes, so a plain lookup leaks no usable timing (preimage resistance) —
// the secret never sits in memory as plaintext for comparison.
func tokenIdentity(tok string) (clientIdentity, bool) {
	if tok == "" {
		return clientIdentity{}, false
	}
	sum := sha256.Sum256([]byte(tok))
	id, ok := loadTokenIdentities()[hex.EncodeToString(sum[:])]
	return id, ok
}

// certIdentity returns the CommonName of the client certificate the peer
// presented. Every identity this project mints — `koto pki client` (pki.go)
// and the Makefile's openssl route alike — sets CN, the clients.allow name
// column and the tokens.json key to the SAME name, so the CN is the cert's
// claim about which identity it is. The bool is false when the connection
// carries no TLS peer certificate at all, which cannot happen through the
// real listener (RequireAndVerifyClientCert) and so is a deny, not a skip.
func certIdentity(ctx context.Context) (string, bool) {
	p, ok := peer.FromContext(ctx)
	if !ok || p.AuthInfo == nil {
		return "", false
	}
	ti, ok := p.AuthInfo.(credentials.TLSInfo)
	if !ok || len(ti.State.PeerCertificates) == 0 {
		return "", false
	}
	return ti.State.PeerCertificates[0].Subject.CommonName, true
}

func peerAddr(ctx context.Context) string {
	if p, ok := peer.FromContext(ctx); ok && p.Addr != nil {
		return p.Addr.String()
	}
	return "?"
}

// authFromCtx enforces the bearer token (authentication) and resolves the
// caller's identity. mTLS (cert chain + fingerprint allowlist) is already
// enforced by the TLS layer before any RPC dispatches, so reaching here means
// the peer holds a valid allowlisted client cert.
func authFromCtx(ctx context.Context) (clientIdentity, error) {
	md, _ := metadata.FromIncomingContext(ctx)
	tok := ""
	if vals := md.Get("authorization"); len(vals) > 0 {
		tok = strings.TrimSpace(strings.TrimPrefix(vals[0], "Bearer "))
	}
	id, ok := tokenIdentity(tok)
	if !ok {
		emitLogf("auth", "warn", "rejected call from %s (bad/missing token)", peerAddr(ctx))
		return clientIdentity{}, status.Error(codes.Unauthenticated, "invalid or missing token")
	}
	// The two credentials must name the SAME identity (audit L6). Without
	// this the two layers authenticate independently: any allowlisted cert
	// plus a leaked admin token is admin, and revoking a device means
	// remembering both clients.allow and tokens.json — miss one and the
	// device keeps full access. Binding them makes either revocation
	// sufficient. Fails closed on a connection with no peer certificate.
	cn, ok := certIdentity(ctx)
	if !ok {
		emitLogf("auth", "warn", "rejected call from %s (no client certificate)", peerAddr(ctx))
		return clientIdentity{}, status.Error(codes.Unauthenticated, "no client certificate")
	}
	if cn != id.Name {
		emitLogf("auth", "warn", "rejected call from %s: client cert %q presented %q's token", peerAddr(ctx), cn, id.Name)
		return clientIdentity{}, status.Error(codes.Unauthenticated, "client certificate and token name different identities")
	}
	return id, nil
}

// authBindingPreflight names every identity whose two credentials cannot
// agree, at startup, on the daemon log. The binding above turns a mismatch
// into an Unauthenticated no client would explain to itself, so the operator
// hears about it once when the daemon comes up rather than from a device that
// silently stopped working: a clients.allow name with no tokens.json entry can
// never authenticate, and a tokens.json entry with no allowlisted cert of that
// name can only be used from a cert someone else holds.
func authBindingPreflight() {
	allowNames := map[string]bool{}
	b, err := os.ReadFile(credFile("clients.allow"))
	if err != nil {
		return // no allowlist yet: pre-wizard, nothing to check
	}
	for _, line := range strings.Split(string(b), "\n") {
		f := strings.Fields(line)
		if len(f) >= 2 && !strings.HasPrefix(f[0], "#") {
			allowNames[f[1]] = true
		}
	}
	tokNames := map[string]bool{}
	for _, id := range loadTokenIdentities() {
		tokNames[id.Name] = true
	}
	for n := range allowNames {
		if !tokNames[n] {
			emitLogf("auth", "warn", "identity %q has an allowlisted cert but no tokens.json entry — its calls will be refused (mint one: koto pki client %s)", n, n)
		}
	}
	for n := range tokNames {
		if !allowNames[n] {
			emitLogf("auth", "warn", "identity %q has a token but no cert named %q in clients.allow — its calls will be refused", n, n)
		}
	}
}

// aclLogGroup maps a group-scoped verb's target onto the pb.LogEvent.group
// field. A concrete group name attributes the decision to that group's log;
// the "*" wildcard (a request that reads across every group, e.g. unfiltered
// metrics) is daemon-wide, so it stays unattributed.
func aclLogGroup(target string) string {
	if target == "*" || !validGroupName(target) { // unvalidated request field (audit I4)
		return ""
	}
	return target
}

// aclCheck is the authorization decision for one decoded request: some role
// of the caller must grant the verb, and — for group-scoped verbs — that
// grant must cover the request's target group (acl.go; union semantics).
func aclCheck(ctx context.Context, id clientIdentity, verb string, req any) error {
	target, targeted := targetOf(req)
	roles := strings.Join(id.Roles, ",")
	if rolesAllowed(loadACL(), id.Roles, verb, target, targeted) {
		if targeted {
			emitLogfG("acl", aclLogGroup(target), "info", "%s (roles %s) allowed %s on %q from %s", id.Name, roles, verb, target, peerAddr(ctx))
		} else {
			emitLogf("acl", "info", "%s (roles %s) allowed %s from %s", id.Name, roles, verb, peerAddr(ctx))
		}
		return nil
	}
	if targeted {
		emitLogfG("acl", aclLogGroup(target), "warn", "%s (roles %s) denied %s on %q from %s", id.Name, roles, verb, target, peerAddr(ctx))
		return status.Errorf(codes.PermissionDenied, "roles %s may not call %s on %q", roles, verb, target)
	}
	emitLogf("acl", "warn", "%s (roles %s) denied %s from %s", id.Name, roles, verb, peerAddr(ctx))
	return status.Errorf(codes.PermissionDenied, "roles %s may not call %s", roles, verb)
}

func authUnary(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (any, error) {
	id, err := authFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	if err := aclCheck(ctx, id, verbFromMethod(info.FullMethod), req); err != nil {
		return nil, err
	}
	return handler(ctx, req)
}

// aclStream wraps a ServerStream so the target check runs when the request
// message actually decodes: a streaming RPC's request isn't available at
// interception time (the generated handler calls RecvMsg *after* the
// interceptor chain), so target enforcement has to ride the RecvMsg path.
type aclStream struct {
	grpc.ServerStream
	id   clientIdentity
	verb string
}

func (s *aclStream) RecvMsg(m any) error {
	if err := s.ServerStream.RecvMsg(m); err != nil {
		return err
	}
	return aclCheck(s.Context(), s.id, s.verb, m)
}

func authStream(srv any, ss grpc.ServerStream, info *grpc.StreamServerInfo, handler grpc.StreamHandler) error {
	id, err := authFromCtx(ss.Context())
	if err != nil {
		return err
	}
	verb := verbFromMethod(info.FullMethod)
	// Verb-level gate now (deny a caller none of whose roles grant the verb
	// before the handler runs); target-level gate rides RecvMsg once the
	// request message exists. For targetless streams (watch_state,
	// subscribe_logs) this first check is the whole decision.
	if !anyGrant(loadACL(), id.Roles, verb) {
		roles := strings.Join(id.Roles, ",")
		emitLogf("acl", "warn", "%s (roles %s) denied %s from %s", id.Name, roles, verb, peerAddr(ss.Context()))
		return status.Errorf(codes.PermissionDenied, "roles %s may not call %s", roles, verb)
	}
	return handler(srv, &aclStream{ServerStream: ss, id: id, verb: verb})
}
