package main

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"net"
	"os"
	"testing"
	"time"

	"clawson-protocol/pb"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/status"
)

// testToken implements PerRPCCredentials for the client side of the test.
type testToken struct{ tok string }

func (t testToken) GetRequestMetadata(context.Context, ...string) (map[string]string, error) {
	if t.tok == "" {
		return map[string]string{}, nil
	}
	return map[string]string{"authorization": "Bearer " + t.tok}, nil
}
func (testToken) RequireTransportSecurity() bool { return true }

// TestAuthMatrix exercises the real serverTLSConfig + auth interceptors + List
// handler end to end over a loopback gRPC connection, using the PKI material
// generated by `make pki-init && make pki-client NAME=goodclient`. It asserts:
// valid cert+token succeeds; valid cert without a token is rejected.
func TestAuthMatrix(t *testing.T) {
	initPaths()
	if _, err := os.Stat(credFile("server.crt")); err != nil {
		t.Skip("no PKI in creds/ — run `make pki-init && make pki-client NAME=goodclient`")
	}
	tok, err := os.ReadFile(credFile("token-goodclient"))
	if err != nil {
		t.Skip("no goodclient token — run `make pki-client NAME=goodclient`")
	}

	tlsCfg, err := serverTLSConfig()
	if err != nil {
		t.Fatalf("serverTLSConfig: %v", err)
	}
	srv := grpc.NewServer(
		grpc.Creds(credentials.NewTLS(tlsCfg)),
		grpc.ChainUnaryInterceptor(authUnary),
		grpc.ChainStreamInterceptor(authStream),
	)
	pb.RegisterClawsonServer(srv, &clawsonServer{})

	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	go srv.Serve(l)
	defer srv.Stop()
	addr := l.Addr().String()

	clientTLS := func() credentials.TransportCredentials {
		cert, err := tls.LoadX509KeyPair(credFile("client-goodclient.crt"), credFile("client-goodclient.key"))
		if err != nil {
			t.Fatal(err)
		}
		caPEM, _ := os.ReadFile(credFile("ca.crt"))
		pool := x509.NewCertPool()
		pool.AppendCertsFromPEM(caPEM)
		return credentials.NewTLS(&tls.Config{
			Certificates: []tls.Certificate{cert},
			RootCAs:      pool,
			ServerName:   "clawson-daemon", // matches the server cert SAN
			MinVersion:   tls.VersionTLS13,
		})
	}

	dial := func(token string) (pb.ClawsonClient, *grpc.ClientConn) {
		cc, err := grpc.NewClient(addr,
			grpc.WithTransportCredentials(clientTLS()),
			grpc.WithPerRPCCredentials(testToken{token}),
		)
		if err != nil {
			t.Fatal(err)
		}
		return pb.NewClawsonClient(cc), cc
	}

	// (a) valid cert + valid token -> success
	t.Run("valid", func(t *testing.T) {
		cl, cc := dial(string(tok))
		defer cc.Close()
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		resp, err := cl.List(ctx, &pb.ListReq{})
		if err != nil {
			t.Fatalf("List with valid creds: %v", err)
		}
		if !resp.GetOk() {
			t.Fatalf("List ok=false: %s", resp.GetError())
		}
	})

	// (b) valid cert, no token -> Unauthenticated
	t.Run("no-token", func(t *testing.T) {
		cl, cc := dial("")
		defer cc.Close()
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_, err := cl.List(ctx, &pb.ListReq{})
		if status.Code(err) != codes.Unauthenticated {
			t.Fatalf("expected Unauthenticated, got %v", err)
		}
	})
}
